Tests/ApolloInternalTestHelpers/SelectionSet+TestHelpers.swift
Tests/ApolloTests/Cache/ReadWriteFromStoreTests.swift
Tests/ApolloTests/GraphQLExecutor_SelectionSetMapper_FromResponse_Tests.swift
apollo-ios/Sources/Apollo/ApolloStore.swift
apollo-ios/Sources/Apollo/GraphQLSelectionSetMapper.swift
apollo-ios/Sources/ApolloAPI/DataDict.swift

This PR removes the stripping of null values from the selection set models. 
This fixes apollographql/apollo-ios#3092. Because data returned from a network request was having null values stripped, when the returned models were then manually written to the cache, the null values were not written. This results in a `missingValue` error when you try to read those objects from the cache later.
This situation could occur if you fetched from the network with a cache policy of `.fetchIgnoringCacheCompletely` and then wrote some of the data to the cache manually. It also occurs in the common case of a fetched object be appended to another list of objects in a cache mutation.
This bug fix revealed another related bug. We previously used `NSNull` to represent null values in a `SelectionSet`, then …

Remove stripping of null values from Selection Set models

---

apollo-ios/Design/3093-graphql-defer.md

@AnthonyMDev, these are the edits we spoke about yesterday to clarify:
* the stored properties are actually psuedo stored-properties
* disabling selection set initializers

rfc: Clarifying edits

---

.githooks/post-checkout

It's annoying, this disables it.

chore: Updates the git hook to disable Xcode opening from `tuist generate`

---

apollo-ios-codegen/Sources/ApolloCodegenLib/Frontend/JavaScript/src/__tests__/deferDirectiveTests.ts
apollo-ios-codegen/Sources/ApolloCodegenLib/Frontend/JavaScript/src/validationRules.ts

The label value of the `@defer` directive is not used when we have a named fragment so we can drop the requirement for a `label` argument to only inline fragments.

refactor: Don't require `label` argument for deferred named fragments

---

Project.swift
Workspace.swift

This cleans this up a bit by including these directly in the Project. 
I was making some other changes to the structure of the codgen packages that was causing build errors, and doing this resolved them.

Include local SPM packages in project, instead of as additional files

---

.github/actions/subtree-split-push/action.yml
git-sh-setup
git-subtree.sh

-Adding the customized git subtree script to use for CI that included the subtree bugfix

fix: Subtree bug

---

apollo-ios/Sources/Apollo/GraphQLResponse.swift

-Fixing the implementation of GraphQLResponse that was causing xcframework build failures with Xcode 15 and Swift 5.9
Closes apollographql/apollo-ios#3154

Fixing hashable implementation of GraphQLResponse

---

apollo-ios-codegen/.github/workflows/pr-close.yml
apollo-ios/.github/workflows/pr-close.yml

-Adding ci script to auto close and comment on PRs in the apollo-ios and apollo-ios-codegen repos
When this PR is merged we will need to manually go disable these workflows in their respective repos until we rollout the new project structure publicly and then we can re-enable them.

Adding ci to auto close PRs

---

.github/workflows/pr-subtree-push.yml

Updating the ci to target the `main` branch of `apollo-ios-codegen` going forward

Change codegen subtree target branch

---

README.md
apollo-ios-codegen/README.md

Adding a callout for reporting issues in the README for `apollo-ios-codegen` and `apollo-ios-dev` as suggested in feedback in apollographql/apollo-ios#3240

Adding issue callout to Readme

---

docs/source/migrations/1.6.mdx

Creating the migration guide for 1.6 release and adding information for the codegen package change from `apollo-ios` to `apollo-ios-codegen`

Adding migration guide for 1.6

---

docs/source/fetching/persisted-queries.mdx

Updating the `apollo-ios` subtree to the `main` branch from that repo one more time in preparation for launch.

Updating subtree to apollo-ios main

---

.github/workflows/ci-tests.yml

Based on the usage report going ahead and adjusting these runners all down to regular runners. Can expect some increase in the average time to run our tests.

Ci runner adjustments

---

Tests/ApolloInternalTestHelpers/SelectionSet+TestHelpers.swift
Tests/ApolloTests/SelectionSetTests.swift
apollo-ios/Sources/Apollo/GraphQLSelectionSetMapper.swift
apollo-ios/Sources/ApolloAPI/DataDict.swift
apollo-ios/Sources/ApolloTestSupport/TestMock.swift

In iOS versions 14.4 and lower, `AnyHashable` coercion does not work. On these platforms, we need to do some additional unwrapping and casting of the values to avoid crashes and other run time bugs.
In addition to doing some more explicit handling of the null values, this PR changes the check for the coercion from 
`#if swift (>=5.4)` to `if #available(iOS 14.5, *)`. It turns out that this is not particularly related to the swift version, but to the iOS version being run.
This PR has been tested locally on iOS 14.4, 14.5, and 17.0.

Handle coercion of AnyHashable 

---

.github/workflows/docs-publish.yml

Moving the docs publish ci job from the `apollo-ios` repo to the `apollo-ios-dev` repo

Moving docs publish ci job

---

.github/workflows/pr-subtree-push.yml

Re-targeting the CI for pagination to `hs/complete-rewrite` branch until that is ready to be merged into main.

Adjust pagination subtree target branch

---

.github/workflows/pr-subtree-push.yml
.github/workflows/release-check.yml

- Adding new job to run nightly and with releases to validate tests on all platforms
- Updated PR Subtree CI to always run each subtree job regardless of if the others fails

Adding new validation job

---

.github/workflows/release-check.yml

Adjusting the Xcode version for the legacy testing nightly job to try and resolve an error with tuist where it appears to have a dependency on Swift Concurrency then switching to a lower version to test iOS 14.4

Adjusting Xcode version for nightly job

---

.github/workflows/pr-subtree-push.yml

Adjusting the pr-subtree-push workflow to be based on 'pull_request_target' instead of 'pull_request' so it runs based in our repo vs the forked repo and can access the secrets needed to perform the work.
Docs here: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

Adjusting PR Subtree Push config

---

apollo-ios-pagination/.github/workflows/pr-close.yml
apollo-ios-pagination/CONTRIBUTING.md

-Adding CI job to auto closes PRs in the pagination repo and direct users to apollo-ios-dev 
-Adding CONTRIBUTING guide that directs users to apollo-ios-dev to contribute to the pagination library

Updating pagination docs and pr close bot

---

docs/source/fetching/mutations.md

This is to standardize the messaging about GraphQL file uploads; from https://github.com/apollographql/apollo-kotlin/pull/5297.

docs: Standardized file upload caveat message

---

Tests/ApolloCodegenTests/CodeGenIR/IRRootFieldBuilderTests.swift
Tests/ApolloCodegenTests/TestHelpers/IRMatchers.swift
apollo-ios-codegen/Sources/IR/IR+RootFieldBuilder.swift

This second PR for https://github.com/apollographql/apollo-ios/issues/3141 refactors the root field builder to build deferred named fragments into the IR. The next PR will generate selection sets from the refactored IR.
* Adds IR matchers for named fragment.
* Refactored logic for `containsDeferredFragment`; moved to where the scope condition is modified to include the defer condition.
* Refactored add selections logic for `.fragmentSpread`

[2/x] Refactor root field builder for deferred named fragments

---

docs/source/code-generation/codegen-configuration.mdx
docs/source/testing/test-mocks.mdx

Related to https://github.com/apollographql/apollo-ios/issues/3262.

docs: Clarify test mocks `absolute` configuration

---

apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPager.swift

This is a bug. Page storage should be keyed by the variables of the query that generated them, not by the initial query.

ApolloPagination: Fix bug where pages were keyed by initial query

---

.github/actions/configure-git/action.yml
.github/workflows/pr-subtree-push.yml

Attempting to fix an issue where the UI on PRs shows me as the person committing subtree changes from CI, but the commits themselves show as coming from "runner" as they should.

Updating git config on action runner

---

docs/source/fetching/subscriptions.mdx

Use the config parameter instead of connectingPayload which has been deprecated. Add the authPayload in the WebSocketTransport.Configuration instead.

docs: Update subscriptions.mdx

---

.github/workflows/docs-publish.yml

Currently the docs publish job triggers twice for every update because its based on pushes to the main branch and our workflow updates and pushes the commit message when PRs are merged triggering a second run. Updating this to be based on merged PRs so that it will only trigger once like our subtree job.

Updating docs publish job

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/PersistedQueriesOperationManifestTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/OperationDescriptor.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/OperationIdentifierFactory.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/LegacyAPQOperationManifestTemplate.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/PersistedQueriesOperationManifestTemplate.swift

Fixes [#apollo-ios/3268](https://github.com/apollographql/apollo-ios/issues/3268)
- Refactor source formatting to improve readability and isolate escaping of characters to JSON manifest format.
- Escape `"` in JSON manifest operation body text

Escape quotation marks in operation manifest body

---

Tests/ApolloCodegenInternalTestHelpers/MockFileManager.swift
Tests/ApolloCodegenTests/ApolloCodegenTests.swift
Tests/ApolloCodegenTests/ApolloSchemaDownloaderInternalTests.swift
Tests/ApolloCodegenTests/CodeGeneration/FileGenerators/FileGeneratorTests.swift
Tests/ApolloCodegenTests/CodeGeneration/FileGenerators/OperationManifestFileGeneratorTests.swift
Tests/ApolloCodegenTests/CodeGeneration/FileGenerators/SchemaModuleFileGeneratorTests.swift
Tests/ApolloCodegenTests/FileManagerExtensionTests.swift

There were some test isolation issues with MockFileManager that were on rare occasions causing data races and failures in some unit tests.
Isolating usages and adding an `NSLock` here fixed them.
I also improved the functionality to decouple the requirement of all closures being called from the use of `strict`.

Test isolation fixes

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift
apollo-ios-codegen/Sources/IR/IR+ScopeDescriptor.swift
apollo-ios-codegen/Sources/IR/IR+SelectionSet.swift
apollo-ios-codegen/Sources/TemplateString/TemplateString.swift

This is an alternative to #113. It's all the same code behaviors and tests are the same. I just took that PR and improved the usage of `TemplateString` in the `SelectionSetTemplate`.

Defer Selection Set Template - Basic (W/clean up)

---

docs/source/tutorial/tutorial-authenticate-operations.mdx

Fixes the tutorial sample code for the `AuthorizationInterceptor` to be compatible with the `1.3` migration.
_From https://apollograph.slack.com/archives/C01BMLR2YBG/p1698955643166659._

docs: Fix tutorial code for 1.3 migration

---

Tests/ApolloInternalTestHelpers/MockOperation.swift
Tests/ApolloTests/RequestChainTests.swift
apollo-ios/Sources/Apollo/RequestChainNetworkTransport.swift

This change is to standardize on the HTTP `accept` header being sent by Apollo iOS and Kotlin clients.
The difference is that the `multipart/mixed` and `application/json` accept types will be included with every query and mutation operation to simplify the request generation and since the response parsing can handle both. This is related to https://github.com/apollographql/apollo-ios/issues/3277.

refactor: HTTP `Accept` header

---

Tests/ApolloTests/Interceptors/MultipartResponseDeferParserTests.swift
Tests/ApolloTests/Interceptors/MultipartResponseParsingInterceptorTests.swift
Tests/ApolloTests/Interceptors/MultipartResponseSubscriptionParserTests.swift
apollo-ios/Sources/Apollo/MultipartResponseDeferParser.swift
apollo-ios/Sources/Apollo/MultipartResponseParsingInterceptor.swift
apollo-ios/Sources/Apollo/MultipartResponseSubscriptionParser.swift

This refactors the multipart response parsers so that each can be built to focus on just their parser data specification logic and common shared logic to process the general multipart response format.
* `MultipartResponseParsingInterceptor` now handles the mechanics of the multipart message chunk parsing.
* `MultipartResponseSpecificationParser` now just requires each specification parser to handle the logic for parsing each data line for a single specification.
_This only includes error based-tests for `MultipartResponseDeferParser` because the executor is not complete. Only once the executor is able to handle deferred fragments will the parsing based-tests be able to succeed._

refactor: Multipart parsers

---

.github/workflows/pr-subtree-push.yml

Adding a fetch before pushing subtree split commits to main to help avoid potential conflicts when pushing.

Adding fetch to subtree job

---

apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift
docs/docc/Apollo.doccarchive/data/documentation/apolloapi/graphqloperation/operationtype-14lsi.json
docs/docc/Apollo.doccarchive/data/documentation/apolloapi/jsonencodable.json
docs/docc/Apollo.doccarchive/data/documentation/apolloapi/swift/optional.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/caseconversionstrategy.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/caseconversionstrategy/camelcase.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/caseconversionstrategy/init(rawvalue:).json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/caseconversionstrategy/none.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/default/enumcases.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/!=(_:_:).json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/camelcase.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/encode(to:).json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/equatable-implementations.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/hash(into:).json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/hashvalue.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/init(from:).json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/init(rawvalue:).json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/none.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.enum/rawrepresentable-implementations.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/enumcases-swift.property.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/fieldaccessors-swift.property.json
docs/docc/Apollo.doccarchive/data/documentation/apollocodegenlib/apollocodegenconfiguration/conversionstrategies/init(enumcases:fieldaccessors:).json

ApolloCodegenConfiguration's documentation had invalid references, which was causing the GenerateDocumentation command to fail.
```
[DEBUG - ApolloCodegenLib:main.swift:77] - Generating documentation for 'ApolloCodegenLib'...
Converting documentation...
/Users/t201595/src/apollo-ios-dev/apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift:672:59: warning: 'EnumCase' doesn't exist at '/ApolloCodegenLib/ApolloCodegenConfiguration/ConversionStrategies'
/Users/t201595/src/apollo-ios-dev/apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift:698:51: warning: 'CaseConversionStrategy' doesn't exist at '/ApolloCodegenLib/ApolloCodegenConfiguration'
/Users/t201595/src/apollo-ios-dev/apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration. …
```

Fix warnings in codegen configuration documentation

---

Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Schema/SchemaConfiguration.swift
Tests/ApolloCodegenTests/CodeGenIR/IRRootFieldBuilderTests.swift
Tests/ApolloCodegenTests/OperationDescriptorTests.swift
Tests/ApolloCodegenTests/OperationIdentifierFactoryTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/OperationDescriptor.swift
apollo-ios-codegen/Sources/IR/IR+RootFieldBuilder.swift

Fixes [#3296](https://github.com/apollographql/apollo-ios/issues/3269).
In some edge cases fragments were not ordered in the same way when creating the operation identifier and source text for the manifest vs. the `definition` in the generated operation model.
This alphabetizes the fragments in both places to ensure a consistent ordering.

Alphabetize fragment ordering in source text

---

Tests/ApolloCodegenTests/ApolloCodegenConfigurationCodableTests.swift
Tests/ApolloCodegenTests/CodeGeneration/Templates/InputObjectTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/InputObjectTemplate.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/RenderingHelpers/String+SwiftNameEscaping.swift

- Add new casing strategy option for InputObjects
Closes apollographql/apollo-ios#3257

Adding InputObject casing strategy

---

.github/workflows/ci-tests.yml

Changing codegen config tests to run with every PR.
Closes apollographql/apollo-ios#3295

Adjusting codegen config test usage

---

.circleci/config.yml
apollo-ios-codegen/.circleci/config.yml
apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
apollo-ios/.circleci/config.yml
docs/renderer/package.json

This is a collection of the following dependency update PRs to avoid multiple subtree push/pulls and having to update each dependency PR once `main` is updated due to the merge rules.
* https://github.com/apollographql/apollo-ios-dev/pull/160
* https://github.com/apollographql/apollo-ios-dev/pull/161
* https://github.com/apollographql/apollo-ios-dev/pull/162
* https://github.com/apollographql/apollo-ios-dev/pull/163
* https://github.com/apollographql/apollo-ios-dev/pull/164
* https://github.com/apollographql/apollo-ios-dev/pull/165
* https://github.com/apollographql/apollo-ios-dev/pull/166
* https://github.com/apollographql/apollo-ios-dev/pull/167
* https://github.com/apollographql/apollo-ios-dev/pull/168
* https://github.com/apollographql/apollo-ios-dev/pull/169

chore(deps): Renovate dependency updates

---

apollo-ios/Sources/Apollo/ApolloInterceptor.swift

As far as I understand, there is no real need for interceptors' ids to be mutable, at least not by the library itself. I decided to leave ids as `var` in all default interceptors though as they're randomly generated and maybe someone has a need to change them to something more descriptive.

Make ApolloInterceptor id requirement read-only

---

Tests/TestCodeGenConfigurations/EmbeddedInTarget-InSchemaModule/Package.swift
Tests/TestCodeGenConfigurations/EmbeddedInTarget-InSchemaModule/test-project.sh
Tests/TestCodeGenConfigurations/EmbeddedInTarget-RelativeAbsolute/PackageOne/Package.swift
Tests/TestCodeGenConfigurations/EmbeddedInTarget-RelativeAbsolute/PackageTwo/Package.swift
Tests/TestCodeGenConfigurations/EmbeddedInTarget-RelativeAbsolute/test-project.sh
Tests/TestCodeGenConfigurations/SwiftPackageManager/Package.swift
Tests/TestCodeGenConfigurations/SwiftPackageManager/test-project.sh
apollo-ios/Sources/ApolloAPI/DataDict.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3301.
I don't know when this stopped working in our test configuration projects but this behaviour is essential to avoid exposing inconvenience warnings to users projects.
I can't find any mention of why the `unsafeFlags` configuration no longer works but I do prefer that the flag is now set on the test script command which is more explicit to the workflow we want for the test - [reference](https://forums.swift.org/t/warnings-as-errors-for-libraries-frameworks/58393).
_I haven't managed to get the behaviour back for Xcode-based projects yet though._

tests: TestCodegenConfigurations projects should fail on warnings

---

docs/source/code-generation/codegen-cli.mdx

* `--schema-name` => `--schema-namespace`
* remove square brackets for required arguments. See https://stackoverflow.com/a/47026846/752630

[docs] small tweaks to apollo-ios-cli doc

---

Tests/ApolloCodegenInternalTestHelpers/IRBuilder+Mocking.swift
apollo-ios-codegen/Sources/IR/IR+SelectionSet.swift

This fixes a retain cycle that was causing memory leaks. This was manually tested to verify that TypeInfo and Entity objects are now properly released when their operations are complete.

[Codegen] Fix retain cycle between Entity and TypeInfo

---

Tests/ApolloTests/RequestChainTests.swift
apollo-ios/Sources/Apollo/RequestChainNetworkTransport.swift

This is the same as https://github.com/apollographql/apollo-ios-dev/pull/232 but limited to non-subscription operations and to be merged into the `feature/defer-execution-networking` branch to only be applicable once all the defer work is merged into `main`.
> The `boundary` portion of the `accept` header has no effect on the `boundary` in the received multipart response so we can remove it and send less data in the request. The multipart response handler is already built to handle any value sent back as the `boundary` and use that to parse the chunks.
> More details in https://github.com/apollographql/router/pull/4395 and https://github.com/apollographql/router/pull/4447.

chore: Removes boundary from accept header

---

.package.resolved
Project.swift

Nimble 13.2.0 has VisionOS support, which will make our adoption of VisionOS support easier.

Update Nimble to 13.2.0

---

apollo-ios/Apollo.podspec
apollo-ios/Package.swift
apollo-ios/Sources/Apollo/Resources/PrivacyInfo.xcprivacy
apollo-ios/Sources/ApolloAPI/Resources/PrivacyInfo.xcprivacy
apollo-ios/Sources/ApolloSQLite/Resources/PrivacyInfo.xcprivacy
apollo-ios/Sources/ApolloWebSocket/Resources/PrivacyInfo.xcprivacy

Closes apollographql/apollo-ios#3328

Add privacy manifest for Apollo targets

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplate_Initializers_Tests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/RenderingHelpers/String+SwiftNameEscaping.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3330.
Adds an underscored alias name to initializer parameters that would conflict with any Swift reserved names. This has only been an issue with `self` specifically within initializers but this enforces the same behaviour for any of the Swift reserved keywords.

fix: Selection set initializer reserved parameter name

---

apollo-ios/.github/workflows/issue-close-user-survey.yml

This skips the user survey comment when an issue is closed if the issue was opened by a maintainer and there were zero comments on the issue at the time. The parameters available through the `issue` event are detailed [here](https://docs.github.com/en/webhooks/webhook-events-and-payloads#issues).
Done to avoid issue survey requests like [this](https://github.com/apollographql/apollo-ios/issues/3328#issuecomment-1919687978).

chore: Update user survey conditions

---

Tests/ApolloPaginationTests/ForwardPaginationTests.swift
apollo-ios-pagination/Sources/ApolloPagination/AsyncGraphQLQueryPagerCoordinator.swift

A special thank you to @ralph-101-dev for finding this issue in a pre-release build of `ApolloPagination`. 
Closes https://github.com/apollographql/apollo-ios/issues/3331
_____
This pull request primarily focuses on modifying how variables are handled in `AsyncGraphQLQueryPagerCoordinator.swift`. The changes involve altering the data types of variables from arrays to sets, which should eliminate the possibility of a mismatch between mis-ordered array outputs. This is especially needed, because the underlying values being pulled from are an unordered dictionary, so multiple invocations of the same function can result in a key-miss. 
The change to production code is a one-liner: We've updated the value of the `variables` variable – which houses the input variables of a given `GraphQLQuery` …

[ApolloPagination] Update variable mapping logic to use a Set instead of an Array

---

apollo-ios-pagination/Sources/ApolloPagination/AsyncGraphQLQueryPager.swift
apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPager.swift

We've detected a memory leak in the implementation of the `Publisher` protocol within `GraphQLQueryPager`. 
Instead of treating this as a custom publisher – which the previous implementation certainly did – we just pare it down and forward to the internal `publisher` property.
A special thank you to @esahmed21 for confirming the leak and making note that it didn't exist in the previous version.
> [!NOTE]
> **Why am I electing to call `subscribe(_:)` instead of `receive(_:)`?**
>
> `subscribe(_:)` in Combine has some additional observation logic that gets triggered before it forwards a subscription, which will ultimately invoke `receive(subscription:)` directly. That logic is important, as it prevents memory cycles & other unexpected outcomes. Apple's Combine docs include the incredible …

[ApolloPagination] Fix memory leak in `GraphQLQueryPager`'s `Publisher` implementation

---

apollo-ios/Sources/Apollo/GraphQLResultNormalizer.swift

`ResultNormalizerFactory` stateless container for static methods. This is better modeled as an `enum` rather than a `struct`, which better guarantees that the type cannot be initialized.

Make `ResultNormalizerFactory` a caseless enum

---

Tests/ApolloPaginationTests/AsyncGraphQLQueryPagerCoordinatorTests.swift
Tests/ApolloPaginationTests/AsyncGraphQLQueryPagerTests.swift
Tests/ApolloPaginationTests/BidirectionalPaginationTests.swift
Tests/ApolloPaginationTests/ConcurrencyTest.swift
Tests/ApolloPaginationTests/ForwardPaginationTests.swift
Tests/ApolloPaginationTests/FriendsQuery+TestHelpers.swift
Tests/ApolloPaginationTests/GraphQLQueryPagerTests.swift
Tests/ApolloPaginationTests/GraphQLQueryPagerTestsCoordinator.swift
Tests/ApolloPaginationTests/Mocks.swift
Tests/ApolloPaginationTests/OffsetTests.swift
Tests/ApolloPaginationTests/ReversePaginationTests.swift
Tests/ApolloPaginationTests/SubscribeTests.swift
apollo-ios-pagination/Sources/ApolloPagination/AsyncGraphQLQueryPager.swift
apollo-ios-pagination/Sources/ApolloPagination/AsyncGraphQLQueryPagerCoordinator.swift
apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPager+Convenience.swift
apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPager.swift
apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPagerCoordinator.swift
apollo-ios-pagination/Sources/ApolloPagination/OffsetBasedPagination/Bidirectional.swift
apollo-ios-pagination/Sources/ApolloPagination/OffsetBasedPagination/ForwardOffset.swift
apollo-ios-pagination/Sources/ApolloPagination/OffsetBasedPagination/OffsetPagination.swift
apollo-ios-pagination/Sources/ApolloPagination/OffsetBasedPagination/ReverseOffset.swift
apollo-ios-pagination/Sources/ApolloPagination/PageExtractionData.swift

Follow-up from https://github.com/apollographql/apollo-ios-dev/pull/267
___
When writing docs in #262, I recognized that support for offset pagination could be better. Specifically:
- We can support more paging types (reverse, bidirectional)
- We can support multi-query paging.
As such, this pull request modifies the OffsetPagination class to be a namespace, just like CursorBasedPagination. We introduce three new structs to facilitate pagination:
- `OffsetPagination.Forward`: Introduced OffsetPagination.Forward structure to represent a forward pagination state. This is identical to the previous contents of OffsetPagination.
- `OffsetPagination.Reverse`: Introduced OffsetPagination.Reverse structure to represent a reverse pagination state.
- `OffsetPagination.Bidirectional`: Introduced …

[ApolloPagination] Remove convenience functions, improved Offset-pagination support

---

apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift

This change is a minor one to clarify which files will be deleted in the single line that most people read.
Read as a whole it's unambiguous which files will be deleted by this option but I think it's easy for readers to gloss over the expanded "This includes" section that goes into detail about when a file will be no longer generated and therefore deleted.

docs: Minor addition to clarify option

---

docs/source/migrations/1.0.mdx

Thanks for great documentation! I fixed links in migration guide that may not function as expected.

docs: Fix non-functional links in migration guide

---

apollo-ios-pagination/README.md

Ads link to Apollo's official documentation page, to show the appropriate subsection for pagination.

Add documentation link to apollo-ios-pagination README

---

Tests/ApolloInternalTestHelpers/MockURLSession.swift
Tests/ApolloTests/Network/URLSessionClientTests.swift
apollo-ios/Sources/Apollo/URLSessionClient.swift

This pull request updates the Apollo `URLSessionClient` adding the ability to optionally provide a session description and/or task description to the `URLSession` , and any subsequent `URLSessionTask` ’s created by the session.
These are helpful when debugging, especially when [analyzing HTTP traffic with Instruments](https://developer.apple.com/documentation/foundation/url_loading_system/analyzing_http_traffic_with_instruments). 
See also:
- [sessionDescription](https://developer.apple.com/documentation/foundation/urlsession/1408277-sessiondescription) 
- [taskDescription](https://developer.apple.com/documentation/foundation/urlsessiontask/1409798-taskdescription)

Session and task descriptions

---

apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPagerCoordinator.swift

This pull request adds the `@Atomic` property wrapper to the `canLoadNext` and `canLoadPrevious` values. 
I noticed these two were popping up in the address sanitizer as a possible data race. I don't believe there was one – but this should at least quiet those warnings. 
___
🤖 Copilot Generated 🤖 
This pull request primarily focuses on improving the thread-safety of the `GraphQLQueryPagerCoordinator` class in the `apollo-ios-pagination` package. The changes involve converting the `canLoadNext` and `canLoadPrevious` properties to atomic properties and updating the way they are mutated.
Here are the most important changes:
Thread-safety improvements:
* [`apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPagerCoordinator.swift`](diffhunk://#diff-55a381cd001c8f61f1ea8b3de40ecb0cfd97d4 …

[ApolloPagination] Declare canLoadPrevious and canLoadNext @Atomic

---

Tests/ApolloTests/Interceptors/MultipartResponseSubscriptionParserTests.swift
apollo-ios/Sources/Apollo/MultipartResponseSubscriptionParser.swift

* Expands the multipart subscriptions test suite to cover all edge cases detailed in https://github.com/apollographql/team-prometheus/pull/261.
* Refactors the parsing logic to handle null `errors`.

update: Expand test suite for multipart subscriptions

---

Tests/ApolloPaginationTests/AsyncGraphQLQueryPagerTests.swift
Tests/ApolloPaginationTests/GraphQLQueryPagerTests.swift
apollo-ios-pagination/Sources/ApolloPagination/AsyncGraphQLQueryPager.swift
apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPager.swift
apollo-ios-pagination/Sources/ApolloPagination/UpdateSource.swift

A bit of an idea I had to ease usage in SwiftUI.
If an `@Observable` view model owns a pager, we cannot observe value changes (`onChange(...)`) of the whole `viewModel`, as the pager breaks conformance. Whether that's a good pattern or not (I think _probably not?_) is a bit besides the point, as I can see some users doing it anyways. 
There are various values stored on the pager classes – the underlying coordinator, the cancellables, etc – but at its core, the underlying data state is what matters, i.e., the value of `_subject`. 
Note: I don't think I can return `lhs._subject.value == rhs._subject.value` since the value is a `Result<(Model, UpdateSource), Error>`. Even if `Model`, `UpdateSource`, and `Error`, are equatable, the tuple value of `(Model, UpdateSource)` is not equatable …

[ApolloPagination] Add conditional `Equatable` conformance to pagers

---

Tests/ApolloPaginationTests/AsyncGraphQLQueryPagerTests.swift
Tests/ApolloPaginationTests/OffsetTests.swift
Tests/ApolloPaginationTests/PagerCoordinator+Erase.swift
apollo-ios-pagination/Sources/ApolloPagination/AsyncGraphQLQueryPager.swift
apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPager+Convenience.swift

**This is a breaking change, and would require a 0.2.0 release**. 
In order to make instantiation of the `AsyncGraphQLQueryPager` easier, we can remove the `async` requirement of the initializer _if_ we also ensure that accesses to `cancellables` becomes atomic. This pull request primarily focuses on the removal of asynchronous initializers and the introduction of `Task` in the `AsyncGraphQLQueryPager` class and its related test classes. The most significant changes include the removal of `await` from `AsyncGraphQLQueryPager` initializers, the introduction of `Task` for subscribing to pager results, and the use of `@Atomic` for thread-safe mutation of `cancellables`.
___
Honestly, it just feels better to instantiate it this way: it opens up the reality of instantiating the object in a …

[ApolloPagination] Remove `async` requirement from `AsyncGraphQLQueryPager` initializers

---

Tests/CodegenCLITests/VersionCheckerTests.swift
apollo-ios-codegen/Sources/CodegenCLI/Extensions/VersionChecker.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3355.
This is the fix to accept version `3` as a valid format for the version checker.

fix: Updates Swift `Package.resolved` file version format

---

.github/workflows/check-pr-metadata.yml

This adds a GitHub Action that will validate some of the metadata for pull requests. Note that it will skip of the PR is a draft and will then only validate once it's marked as "ready for review". As we want to do more to validate PRs we can add to this action under the umbrella of "metadata".

Add GH action to check PR metadata

---

Tests/ApolloTests/Cache/StoreSubscriptionTests.swift
apollo-ios/Sources/Apollo/ApolloStore.swift
apollo-ios/Sources/Apollo/GraphQLQueryWatcher.swift

(Full context in https://github.com/apollographql/apollo-ios/issues/3350.)
Apollo Kotlin currently provides a public [`changedKeys`](https://github.com/apollographql/apollo-kotlin/blob/v4.0.0-beta.5/libraries/apollo-normalized-cache/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/ApolloStore.kt#L27-L30) property to get notified when objects in the ApolloStore change. Internally, iOS has had a similar facility, too -- but it hasn't been `public` until now.

Provide a direct means to observe changes in ApolloStore

---

apollo-ios/Sources/Apollo/Resources/PrivacyInfo.xcprivacy
apollo-ios/Sources/ApolloAPI/Resources/PrivacyInfo.xcprivacy
apollo-ios/Sources/ApolloSQLite/Resources/PrivacyInfo.xcprivacy
apollo-ios/Sources/ApolloWebSocket/Resources/PrivacyInfo.xcprivacy

Fixes https://github.com/apollographql/apollo-ios/issues/3359.
I re-read [Apple's privacy manifest files documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) and it looked like we were declaring arrays but not completing them correctly. This appears to be what made the manifests appear invalid. This change is simply to remove those arrays, leaving the parent keys empty.

fix: Remove empty arrays from privacy manifests

---

apollo-ios-codegen/Sources/IR/IR+EntitySelectionTree.swift

This PR refactors the `EntitySelectionTree` in `apollo-ios-codegen`.
The conditions for merging selections were revisited. The use of `scopeConditions` was removed from the part of the code where the node's scope is checked if it is deferred. Instead, the condition to add merged inline fragments was moved under the child case, specifically when the child case is selections.
Unit tests pass
This is a significant performance improvement as it removes an entire additional iteration through all the conditional scopes in the tree.
---

Remove redundant iteration in EntitySelectionTree merging algorithm

---

apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPager.swift
apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPagerCoordinator.swift

For API consistency, it makes sense that both `fetch` and `refetch` have completion blocks to indicate when their operations are completed. If we think about the way that the `Async` variant works, we always have a "completion" signal in the form of the `await` – whereas we don't for `fetch` and `refetch` in the `GraphQLQueryPager`. 
____
Related: https://github.com/apollographql/apollo-ios/issues/3349
___
Changes in `GraphQLQueryPager.swift`:
* [`public class GraphQLQueryPager<Model>: Publisher {`](diffhunk://#diff-15b3e5571b28a433475df3ef139318cd9aa539ef1302cd4e4600639fbb8d57aaL232-R245): The `refetch` and `fetch` methods have been updated to include two new parameters: `callbackQueue` and `completion`. This allows users to specify a dispatch queue on which the completion callback …

[ApolloPagination] Add completion callbacks to fetch and refetch in GraphQLQueryPager for API Consistency

---

Tests/ApolloPaginationTests/AsyncGraphQLQueryPagerTests.swift

Noticed this locally, decided to just quickly tackle it.

[ApolloPagination] Squash warnings in the test suite around unnecessary `await`s

---

Tests/ApolloCodegenTests/CodeGenIR/IRFieldCollectorTests.swift
Tests/ApolloCodegenTests/CodeGenIR/IRNamedFragmentBuilderTests.swift
Tests/ApolloCodegenTests/TestHelpers/IRMatchers.swift
Tests/ApolloCodegenTests/TestHelpers/LineByLineComparison.swift
Tests/ApolloTests/JSONValueMatcher.swift
Tests/ApolloTests/OperationMessageMatchers.swift
Tests/CodegenCLITests/Matchers/ErrorMatchers.swift

Nimble recently deprecated/renamed `Predicate` to `Matcher`, along with `PredicateResult` to `MatcherResult`. This PR fixes the depreciation warnings by renaming all instances.

Migrate deprecated Nimble types

---

apollo-ios/Sources/ApolloAPI/GraphQLOperation.swift
apollo-ios/Sources/ApolloAPI/SchemaTypes/Interface.swift
apollo-ios/Sources/ApolloAPI/SchemaTypes/Object.swift
apollo-ios/Sources/ApolloAPI/SchemaTypes/Union.swift

Changes in Swift 5.10 and Xcode 15.3 improved the complete concurrency checking functionality in preparation for Swift 6.0. When using Apollo in a project with complete concurrency checking enabled, many warnings are surfaced for some of the generated schema types such as `Interface`, `Object`, and `Union`. These types are simple `struct`s with no mutability semantics, so they can adopt `Sendable` without any further changes or concerns. The same goes for `OperationDefinition` and `OperationDocument` types used in generated queries, mutations, and fragments.

Add Sendable conformance to some basic SchemaTypes

---

docs/source/caching/cache-setup.mdx

Related to https://github.com/apollographql/apollo-ios/issues/3365.
* Adds a note to the [`InMemoryNormalizedCache ` cache documentation](https://www.apollographql.com/docs/ios/caching/cache-setup#inmemorynormalizedcache) re. auto-eviction policies
* Updates another note in the same page to use the new `<note>` tag

docs: In-memory cache note

---

Tests/ApolloCodegenTests/ApolloSchemaDownloadConfigurationCodableTests.swift

When replying to [this forum question](https://community.apollographql.com/t/fetch-schema-giving-error-when-downloading-the-schema-from-server/7385) I realized we don't have a schema download test using GET; this PR adds one.

test: Adds schema download test using GET http method

---

.package.resolved
Project.swift
apollo-ios-codegen/Package.swift
apollo-ios/Apollo.podspec
apollo-ios/Package.swift

Closes https://github.com/apollographql/apollo-ios/issues/3320.
With [SQLite.swift being updated to support visionOS](https://github.com/stephencelis/SQLite.swift/releases/tag/0.15.1) this:
* Updates our SQLite.swift dependency version
* Adds `visionOS` platform declarations
* Updates other dependency versions

feature: Enable visionOS Support

---

Tests/ApolloTests/Cache/WatchQueryTests.swift
apollo-ios/Sources/Apollo/ApolloClient.swift
apollo-ios/Sources/Apollo/ApolloClientProtocol.swift
apollo-ios/Sources/Apollo/GraphQLQueryWatcher.swift

This PR adds a `refetchOnFailedUpdates` to `GraphQLQueryWatcher`. When this is set to `false`, network fetches will no longer occur if the cache load for updates to a watched object fails. This features was added at the request of @jimisaacs.

Add refetchOnFailedUpdates to query watcher

---

Tests/ApolloTests/Interceptors/IncrementalJSONResponseParsingInterceptorTests.swift
apollo-ios/Sources/Apollo/CacheWriteInterceptor.swift
apollo-ios/Sources/Apollo/IncrementalJSONResponseParsingInterceptor.swift

Closes https://github.com/apollographql/apollo-ios/issues/3362.
With only minor changes we've got cache writing successfully working for the partial and incremental responses of operations using `@defer`.
* Adds storage for cache records to `IncrementalJSONResponseParsingInterceptor` so they can be merged when multiple incremental results are received in the same response.
* Removes the early-exit in `CacheWriteInterceptor` to disable cache writes for operations using `@defer`.
* Adds tests for incremental cache writes.

defer: Adds incremental response cache writes

---

Tests/ApolloTests/GraphQLExecutor_SelectionSetMapper_FromResponse_Tests.swift
apollo-ios/Sources/Apollo/FieldSelectionCollector.swift
apollo-ios/Sources/ApolloAPI/Selection+Conditions.swift

Conditions on a deferred fragment were not correctly being evaluated during field collection. This meant that deferred fragments would always be collected into `_deferredFragments` regardless of any condition. It's now fixed and deferred fragments are not collected if the condition would evaluate to false meaning the deferred fragment should never be expected to be received.

fix (defer): deferred fragment condition evaluation

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/InputObjectTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/RenderingHelpers/GraphQLInputField+Rendered.swift

Fixes [#2997](https://github.com/apollographql/apollo-ios/issues/2997).
The Kotlin codegen generates the parameter for that field with a default value of nil, so that if the user doesn’t pass a value, the field is omitted from the request and the schema side default value is used. This provides parity with Kotlin client functionality.

Generate nil default value for input field w/default value in schema

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/InterfaceTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/InterfaceTemplate.swift

Fixes [#3375](https://github.com/apollographql/apollo-ios/issues/3375)
`Interface` should be namespaced to `ApolloAPI`.

Namespace ApolloAPI in InterfaceTemplate

---

.github/actions/run-cocoapods-integration-tests/action.yml
docs/shared/setup-codegen/single-panel.mdx

Closes https://github.com/apollographql/apollo-ios/issues/3382.
There isn't much detail in that issue on what the actual problem is so I did an audit on where we might still be using `--schema-name` and found two outdated references; migration guide and CI action. This PR simply updates those to use the newer `--schema-namespace`.

chore: Update deprecated `--schema-name` property references

---

apollo-ios/ApolloTestSupport.podspec

Looks like we'd simply forgotten to add a deployment target for visionOS to the ApolloTestSupport podspec. This brings it up to support the same deployment platforms as the Apollo podspec and all SPM packages.

fix: Adds visionOS deployment to ApolloTestSupport podspec

---

Tests/ApolloTests/CacheKeyResolutionTests.swift
Tests/ApolloTests/DataLoaderTests.swift
Tests/ApolloTests/ExecutionSources/NetworkResponseExecutionSource_OpaqueObjectDataWrapper_Tests.swift
Tests/ApolloTests/GraphQLExecutor_ResultNormalizer_FromResponse_Tests.swift
Tests/ApolloTests/GraphQLExecutor_SelectionSetMapper_FromResponse_Tests.swift
Tests/ApolloTests/PossiblyDeferredTests.swift
apollo-ios/Sources/Apollo/ExecutionSources/NetworkResponseExecutionSource.swift
apollo-ios/Sources/Apollo/FieldSelectionCollector.swift
apollo-ios/Sources/Apollo/GraphQLExecutionSource.swift
apollo-ios/Sources/Apollo/GraphQLExecutor.swift
apollo-ios/Sources/Apollo/GraphQLResultAccumulator.swift
apollo-ios/Sources/Apollo/GraphQLSelectionSetMapper.swift
apollo-ios/Sources/Apollo/PossiblyDeferred.swift
apollo-ios/Sources/ApolloTestSupport/TestMock.swift
apollo-ios/Sources/ApolloTestSupport/TestMockSelectionSetMapper.swift

This adds @_spi(Execution) to the `GraphQLExecutor` and related types. This is consumed by `ApolloTestSupport` to enable building in non-test builds (eg. swift UI previews) by removing `@testable`.

Add @_spi(Execution) to executor for import in test mocks

---

.github/workflows/ci-tests.yml
apollo-ios/ROADMAP.md

Integration tests need node 12.22.10 which does not have an image for arm64 devices. We need to rollback to using the macos-13 image for this job.

Set integration tests to run on macos-13

---

apollo-ios/Sources/Apollo/NetworkFetchInterceptor.swift
apollo-ios/Sources/Apollo/URLSessionClient.swift

This PR adds task descriptions based on the operation type, name and identifier. [Task descriptions](https://developer.apple.com/documentation/foundation/urlsessiontask/1409798-taskdescription) are helpful in disambiguation `URLSessionTask`s in Instruments and debugging in Xcode.

Default task descriptions

---

Tests/ApolloTests/RequestChainTests.swift
apollo-ios/Sources/ApolloSQLite/SQLiteDotSwiftDatabase.swift

In Xcode 16, or rather Foundation in the iOS 18/etc. SDKs, there’s a new [`Expression` type](https://developer.apple.com/documentation/foundation/expression). The SQLite library also expose this type. This caused an issue compiling the `SQLiteDotSwiftDatabase.swift` file, as it imports both libraries. This PR disambiguates it for the compiler.
With this change the project once again builds with Xcode 16.

Fix building ApolloSQLite with Xcode 16b1

---

.package.resolved

This updates the Swift Collections dependency to `1.1.1` because the [release notes](https://github.com/apple/swift-collections/releases/tag/1.1.1) specifically mention the release resolving issues uncovered since the `1.1.0` release.

chore: Update Swift Collections dependency

---

.github/workflows/create-release-pr.yml

This is the first step in automating our release process as much as possible. The plan is to have this manually triggered CI job that can create the initial PR and handle all the basic tasks associated with that. Then a separate CI job that will be triggered on merge of release PRs to handle the tasks associated with that (tagging, creating release on github repo etc)
Currently planning to leave CHANGELOG handling as a manual process and get as many other parts of the CI process as possible automated and then revisit the possibility of automating CHANGELOG handling as well.
Sample Release PR created by this workflow: https://github.com/apollographql/apollo-ios-dev/pull/394
The "Things to do as part of releasing" section will be the focus of the workflow that triggers from merging the …

cI: Release Automation Step 1

---

.github/actions/repo-dispatch/action.yml
.github/workflows/pr-subtree-push.yml
.github/workflows/publish-release.yml

This PR sets up the publishing portion of automating our release process. Some of the steps may (likely will) require some tweaking once we have had a chance to test it in practice to ensure everything is configured exactly correct, using proper tokens etc.

ci: Setting up release publishing

---

apollo-ios/Sources/ApolloAPI/SelectionSet.swift

- Adding `debugDescription` through `CustomDebugStringConvertible` to `SelectionSet`
Closes apollographql/apollo-ios#3374

Adding debugDescription to SelectionSets

---

.github/workflows/ci-tests-xcode-beta.yml

I've duplicated our `ci-tests.yml` action and edited it to run on the beta Xcode `16.0` which is available on the `macos-latest` image; the integration tests are still on `macos-13` due to the Node version limitation.
This should allow us to manually trigger the workflow (for now) against branches that either fix builds for Xcode 16 or something we care about checking for compatibility for. I didn't make it part of the required PR checks because there are failures at the moment and it would hold up everything. Once we get the code stable for Xcode 16 we should look at making it a required check on all PRs.

ci: Adds a manually triggered action for Xcode Beta version testing

---

.github/workflows/ci-tests-xcode-beta.yml

I'm assuming this maybe has to be the full version number?

ci: Fix Xcode beta version number

---

docs/source/pagination/introduction.mdx

Adding a note about needing to include the `apollo-ios-pagination` package in order to use pagination.
Also added quotes to PR title to test handling that in our PR merge workflow.
Closes apollographql/apollo-ios#3407

Adding usage note to "Pagination Introduction" docs

---

.github/actions/subtree-split-push/action.yml

Adjusting PR title usage in one more spot to handle escaping

PR Title escaping update

---

Tests/TestPlans/Apollo-CITestPlan.xctestplan
Tests/TestPlans/Apollo-UnitTestPlan.xctestplan

Disabling the `testCancellingTaskThroughClientDoesNotCallCompletion` for now because it is flaky and failing inconsistently.

Disabling flaky test

---

apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package-lock.json

This is an attempt to resolve the transitive failures we see on the 'Verify Frontend Bundle Latest' CI job step. I think it comes down to version differences of the node dependencies installed on CI at the time of testing because we do not commit the `package-lock.json` file.
This PR now adds that file and we'll monitor to see if the transitive failure still comes up.

chore: Commit GraphQLCompiler package-lock.json

---

Tests/ApolloTests/Cache/DeferOperationCacheWriteTests.swift
apollo-ios-codegen/Sources/IR/IR+ScopeDescriptor.swift
apollo-ios/Sources/Apollo/FieldSelectionCollector.swift
docs/source/fetching/defer.mdx

Getting local cache mutation cache writes working with operations that use `@defer`.
* Removes the `assertionFailure` and collects fields to execute if the deferred fragment is marked as fulfilled.
* Updates documentation for cache write caveat (using private `DataDict` initializer).
* Removes old TODO markers, test reminders, etc.

defer: Local cache mutation writes

---

apollo-ios-codegen/Sources/GraphQLCompiler/GraphQLError.swift

When a GraphQLError from the JS parsing step is a “Too many validation errors” error, there is no `source` in the error object. This was causing a crash. We should make this an optional parameter and check for it to avoid this edge case.
Writing a unit test for this is difficult because we would need to write a large schema document with many errors in it. This is a minor edge case, and I think that an inline comment explaining the problem should suffice to prevent regressions here.

Fix crash when GraphQLError is “too many validation errors”

---

Tests/ApolloTests/RequestChainTests.swift
apollo-ios/Sources/Apollo/CacheWriteInterceptor.swift

The defer execution changes merged from PR https://github.com/apollographql/apollo-ios-dev/pull/413 introduced a bug where the cache write interceptor would throw if no cache records were returned. This is incorrect as it is a valid response for the `data` key to be missing and only an `errors` key returned, such as in the case of a [request error](https://spec.graphql.org/draft/#sec-Errors.Request-Errors).
This changeset is to allow the cache write interceptor to gracefully handle missing cache records and only publish records to the cache if they were returned from parsing.
* Adds a test that verifies the default interceptor chain successfully parses a request error
* Removes deprecation attribute for `noResponseToParse` error
* Removes error `missingCacheRecords` since it's no longer …

fix: Cache write interceptor should gracefully handle missing cache records

---

docs/source/tutorial/tutorial-add-graphql-schema.mdx

The URL we had does not work in explorer. It is also different from the URL used in the schema download configuration JSON sample.

docs: Fixes the tutorial server URL

---

.github/workflows/create-release-pr.yml
.github/workflows/publish-release.yml

When doing the release for 1.14.0 I noticed that there was no draft release created in the `apollo-ios-codegen` repo and I had to manually create releases for 1.13.0 and 1.14.0. This should now do that automatically for us.

chore: Create draft release for `apollo-ios-codegen` when publishing a release

---

apollo-ios/Sources/ApolloSQLite/JournalMode.swift
apollo-ios/Sources/ApolloSQLite/SQLiteDatabase.swift
apollo-ios/Sources/ApolloSQLite/SQLiteDotSwiftDatabase.swift

Closes https://github.com/apollographql/apollo-ios/issues/3399.
There are many other [`PRAGMA` commands that sqlite supports](https://www.sqlite.org/pragma.html) so there were a few ways this could have been implemented:
1. Make the `execute` or `run` functions public on `SQLiteDatabase` but this is potentially the most destructive as it's a wide open door to executing anything against the connected database.
2. Create a new `setPragma` function that would execute the `PRAGMA <statement>` command. This narrows the scope to only `PRAGMA` statements but this is also potentially destructive as I am not familiar with all the pragma statements and their effects.
3. Create a new `setJournalMode` function that only allows the journal mode to be set. This is very narrow in scope but the safest …

feature: Add function to set journal mode on sqlite databases

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/DeferredFragmentsMetadataTemplateTests.swift
Tests/ApolloCodegenTests/CodeGeneration/Templates/OperationDefinitionTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/DeferredFragmentsMetadataTemplate.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/OperationDefinitionTemplate.swift

The use of the `\(section:)` interpolation method for `DeferredFragmentsMetadataTemplate` was causing the new line at the end of the generated operation files to be deleted. This corrects that.

Fix newline at end of generated operation

---

.github/workflows/ci-tests-xcode-beta.yml

I noticed that the [`macos-latest` image on GH](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#xcode) has updated their Xcode 16 beta version to `16A5202i` (beta 3). That reminded me of the [very weird unit test failures](https://github.com/apollographql/apollo-ios-dev/actions/runs/9880627407/job/27294735846#step:5:1369) I was getting on Xcode 16 beta 1 and 2 in my PR #417; I made a note to revisit this once the GH image had been updated to beta 3 because I could simulate the CI failures locally with 1 and 2 but 3 passed all tests as expected.

ci: Re-enable unit tests on Xcode 16.0 beta

---

apollo-ios/Sources/Apollo/HTTPResponse.swift
apollo-ios/Sources/Apollo/IncrementalJSONResponseParsingInterceptor.swift
apollo-ios/Sources/Apollo/JSONResponseParsingInterceptor.swift

When the `legacyResponse` property of `HTTPResponse` was deprecated setting the value was also removed; this was incorrect as it created a hidden breaking change for interceptors that might have been using the value.
The value cannot simply be set though, as it was before, because of Swift's inability to disable the deprecation warning. Instead there is now an internal property that stores the legacy response value and `legacyResponse` becomes a computed property that simply forwards the new internal property value.
The `cacheRecords` property that was added to eliminate the need to re-parse the legacy response has also been made public for interceptors that need cache records and do not want to have to parse the response a second time.

fix: `legacyResponse` property

---

.github/workflows/ci-tests-xcode-beta.yml
.github/workflows/ci-tests.yml

I've noticed that if the `build-and-test` step fails there is no collection of the build logs which makes it impossible to diagnose a test failure. This change is to indicate that the job should still continue even if one of the unit test (Swift or JS) steps fails.

ci: Continue on error if unit test fails

---

apollo-ios/Sources/Apollo/ApolloStore.swift

There is a leak in fileprivate lazy var loader: DataLoader<CacheKey, Record> because the method implicitly uses self. Making the capture explicit and breaking the retain cycle here. This was also covered in WWDC 2024 analyze heap memory talk https://developer.apple.com/wwdc24/10173?time=1748
Leak detected via instruments

Fix a leak related to use of function used in a closure

---

Tests/ApolloTests/CacheKeyResolutionTests.swift
apollo-ios/Sources/ApolloAPI/ObjectData.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3414
Checking whether `AnyHashable` can be cast to a `Bool` is not enough to infer behaviour from the original type. The only way to do that is to compare against the two possible `Bool` values; `true` and `false`. This is possible because of the way `AnyHashable` does equality comparison.

fix: `ObjectData` type check

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3424.
Refactored the selection set template scope comparison to account for an edge case in merged sources.

fix: `SelectionSetTemplate` scope comparison

---

Tests/ApolloCodegenTests/ApolloCodegenConfigurationCodableTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift

This fixes a decoding error when the deprecated option `localCacheMutations` is present in the JSON config. We should ignore the key when decoding, but not throw an error if it's present.
This issue was surfaced from [this comment on an unrelated issue](https://github.com/apollographql/apollo-ios/issues/3428#issuecomment-2305590461).

Bring back deprecated CodingKey for localCacheMutation in selectionSetInitializers

---

apollo-ios/Sources/Apollo/ApolloClient.swift

When the `watch(query:cachePolicy:context:callbackQueue:resultHandler:)` function was deprecated the new function introduced a single new parameter with a default which meant that using the minimally required parameters to call the function (`watch(query:resultHandler:)`) matches both signatures. This generates a perpetual deprecation warning with no way to get rid of it other than to use the new `refetchOnFailedUpdates` parameter in the function call.
Marking the deprecated function with `@_disfavoredOverload` allows the minimally required function call to be used again without the deprecation warning. I'm really surprised that nobody has complained about this before.

fix: Disfavour deprecated `watch` function

---

apollo-ios/Sources/Apollo/JSONRequest.swift

Closes https://github.com/apollographql/apollo-ios/issues/3432.
There is currently no way for a user to opt-out of the URLRequest default caching behaviour. This PR simply sets a comparable cache policy on `URLRequest` for `GET` requests.
* `returnCacheDataElseFetch` == `returnCacheDataElseLoad`: Direct comparison
* `fetchIgnoringCacheData` == `reloadIgnoringLocalCacheData`: The Apollo iOS version of this cache policy means that only the request will ignore cached data but the response will still be cached. It seems correct to ignore any iOS cached responses but still use any remote (CDN) cached responses.
* `fetchIgnoringCacheCompletely` == `reloadIgnoringLocalAndRemoteCacheData`: The Apollo iOS version of this cache policy will ignore cached data for the request but it will also not …

enhancement: Set URLRequest cache policy on GET requests

---

apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift
docs/source/code-generation/codegen-configuration.mdx

I noticed today that our [codegen configuration documentation](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration) is a little out-of-date, this fixes that:
* Removed references to experimental client controlled nullability
* Added reference to experimental field merging
* Added reference to schema customization in output properties list
* Changed indentation from tab to space for JSON samples (should solve some alignment issues)

docs: Update codegen configuration documentation

---

Tests/ApolloTests/ObjectDataTransformerTests.swift
apollo-ios/Sources/ApolloAPI/ObjectData.swift

Cherry-picking the same type data check from `ObjectData` into `ListData`. See https://github.com/apollographql/apollo-ios-dev/pull/459.

fix: Cherry pick `ObjectData` type check to `ListData`

---

apollo-ios-codegen/Package.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/SwiftPackageManagerModuleTemplate.swift
apollo-ios-pagination/Package.swift
apollo-ios/Package.swift

* Adds a comment to the Apollo libraries indicating which version of Xcode provides the required Swift Tools version.
* Updates the SPM package template swift-tools-version to match the Apollo libraries.

chore: Required swift-tools-version update

---

docs/source/code-generation/codegen-configuration.mdx
docs/source/config.json
docs/source/development/selection-set-initializers.mdx

Adding documentation for the configuration of Selection Set Initializers.
_Still to be added is a section on the usage of Selection Set Initializers in the "Development & Testing" section of the docs._

docs: Selection Set Initializers

---

.github/workflows/ci-tests-xcode-beta.yml
.github/workflows/ci-tests.yml

This is a revert and improvement of #458.
* `continue-on-error` inaccurately reflects the test outcome as succeeded. [Here is the workflow summary](https://github.com/apollographql/apollo-ios-dev/actions/runs/10854978416) for #479 which is _correctly_ failing a codegen test but _incorrectly_ showing the entire CI run as successful. At the time of doing #458 I'd assumed it would still fail the step but allow other downstream jobs to still go ahead, turns out that's not how it works. 😬 
* Uses `failure()` as the `if` condition for the downstream logging jobs.

ci: Fix GH action to accurately show test result

---

Sources/AnimalKingdomAPI/AnimalKingdomAPI/Package.swift
Sources/GitHubAPI/GitHubAPI/Package.swift
Sources/StarWarsAPI/StarWarsAPI/Package.swift
Sources/StarWarsAPI/StarWarsAPI/Sources/Operations/Queries/HeroFriendsDetailsUnconditionalAndConditionalInclusionQuery.graphql.swift
Sources/SubscriptionAPI/SubscriptionAPI/Package.swift
Sources/UploadAPI/UploadAPI/Package.swift
Tests/ApolloCodegenTests/CodeGeneration/Templates/SwiftPackageManagerModuleTemplateTests.swift

The `swift-tools-version` number in generated package manifests was recently updated in #479. We didn't update the test though; _it's debatable whether this test actually has much value to be honest._ Also related to #483.

fix: Update Codegen generated SPM swift-tools-version check

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplate_LocalCacheMutation_Tests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3443.
Simply removes the setter for mutable inline fragments (type conditions). The correct way to initialize with the type condition is to use `asRootEntityType`.

fix: Removes local cache mutation type condition setter

---

docs/source/caching/cache-key-resolution.mdx
docs/source/fetching/fetching-data.mdx
docs/source/fetching/operation-arguments.mdx
docs/source/project-configuration/modularization.mdx
docs/source/project-configuration/schema-types.mdx

Found some broken links from a recent docs review.

docs: Post review fixes

---

Tests/ApolloInternalTestHelpers/SQLiteTestCacheProvider.swift
Tests/ApolloInternalTestHelpers/SelectionSet+TestHelpers.swift
Tests/ApolloInternalTestHelpers/TestCacheProvider.swift
Tests/ApolloPerformanceTests/ParsingPerformanceTests.swift
Tests/ApolloTests/Cache/CacheDependentInterceptorTests.swift
Tests/ApolloTests/Cache/DeferOperationCacheReadTests.swift
Tests/ApolloTests/Cache/DeferOperationCacheWriteTests.swift
Tests/ApolloTests/Cache/FetchQueryTests.swift
Tests/ApolloTests/Cache/LoadQueryFromStoreTests.swift
Tests/ApolloTests/Cache/ReadWriteFromStoreTests.swift
Tests/ApolloTests/Cache/SQLite/CachePersistenceTests.swift
Tests/ApolloTests/Cache/StoreConcurrencyTests.swift
Tests/ApolloTests/Cache/WatchQueryTests.swift

This adds `async/await` support and improves the teardown logic of this test helper.

Add async/await to TestCacheProvider

---

Tests/ApolloInternalTestHelpers/MockSchemaMetadata.swift
Tests/ApolloInternalTestHelpers/TestObserver.swift
Tests/ApolloPaginationTests/AsyncGraphQLQueryPagerCoordinatorTests.swift
Tests/ApolloPaginationTests/BidirectionalPaginationTests.swift
Tests/ApolloPaginationTests/ForwardPaginationTests.swift
Tests/ApolloPaginationTests/GraphQLQueryPagerCoordinatorTests.swift
Tests/ApolloPaginationTests/ReversePaginationTests.swift
Tests/ApolloPaginationTests/SubscribeTests.swift
Tests/ApolloServerIntegrationTests/StarWarsServerCachingRoundtripTests.swift
Tests/ApolloServerIntegrationTests/StarWarsServerTests.swift
Tests/ApolloServerIntegrationTests/StarWarsWebSocketTests.swift
Tests/ApolloTests/Cache/ReadWriteFromStoreTests.swift
Tests/ApolloTests/Cache/WatchQueryTests.swift
Tests/ApolloTests/CacheKeyResolutionTests.swift
Tests/ApolloTests/GraphQLExecutor_ResultNormalizer_FromResponse_Tests.swift
Tests/ApolloTests/GraphQLExecutor_SelectionSetMapper_FromResponse_Tests.swift
Tests/ApolloTests/Network/URLSessionClientTests.swift
Tests/ApolloTests/SelectionSetTests.swift
Tests/ApolloTests/SelectionSet_JSONInitializerTests.swift

This is a fix for broken tests due to #493 being accidentally merged too early.
In order to properly support Swift Concurrency, tests that alter the MockSchemaMetadata must be marked as `MainActor`.

Fix MockSchemaMetadata actor isolation

---

apollo-ios/Sources/ApolloSQLite/SQLiteDatabase.swift
apollo-ios/Sources/ApolloSQLite/SQLiteDotSwiftDatabase.swift
apollo-ios/Sources/ApolloSQLite/SQLiteNormalizedCache.swift

This uses `insertMany` to batch the writing of records to the SQLite cache. Previously we were running separate DB transaction/query for each individual record written. This should significantly improve performance of File I/O for cache writes.
We are investigating utilizing the [Benchmarks](https://github.com/ordo-one/package-benchmark/tree/main) package at some point in the future to measure the performance improvement, but that project is blocked for now and we should still release this performance improvement in the mean time.

Batch writing of records to SQLite store

---

docs/source/index.mdx

Broken "Getting started" links on [this](https://www.apollographql.com/docs/ios) page. I _think_ removing the trailing slash should do it?

docs: Fix broken link

---

apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPagerCoordinator.swift

In `CompletionManager.deinit` we directly call each of the completions but instead we should use `.execute` to ensure that the completion closures are being called in the given queue.

Call the completions in the given callback queue when `CompletionManager` is getting deinitialized

---

Tests/ApolloInternalTestHelpers/String+Data.swift
Tests/ApolloTests/DeferTests.swift
Tests/ApolloTests/Interceptors/MultipartResponseDeferParserTests.swift
Tests/ApolloTests/Interceptors/MultipartResponseSubscriptionParserTests.swift
Tests/ApolloTests/Network/URLSessionClientTests.swift
Tests/ApolloTests/RequestChainTests.swift
apollo-ios/Sources/Apollo/MultipartResponseParsingInterceptor.swift
apollo-ios/Sources/Apollo/URLSessionClient.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3453.
The multipart message parsing code was not splitting message chunks at the correct boundary. It would only look for the [dash boundary (`--graphql`)](https://github.com/apollographql/team-clients/blob/9e5914a2eb9e55e1a0882edeab45188acbf76c0e/rfcs/MultipartSubscriptionsTests.md#conventions) instead of the [full delimiter (`\r\n--graphql`)](https://github.com/apollographql/team-clients/blob/9e5914a2eb9e55e1a0882edeab45188acbf76c0e/rfcs/MultipartSubscriptionsTests.md#conventions). This meant that if the dash boundary was present in the message body the chunk would be split causing a parsing error.
* Multipart delimiter changed to match the RFC specifications.
* Refactored property and function names to match multipart RFC …

fix: Multipart delimiter boundary parsing

---

docs/source/code-generation/codegen-cli.mdx

This is in response to feedback from the [Fetch Schema](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#fetch-schema) documentation page.

docs: Adds schema download configuration details

---

Tests/ApolloTests/WebSocket/WebSocketTests.swift
apollo-ios/Sources/ApolloWebSocket/WebSocketTransport.swift

Closes https://github.com/apollographql/apollo-ios/issues/2274
Closes https://github.com/apollographql/apollo-ios/issues/2447
There is a sequence of events where the caller unsubscribes which removes their ID from `subscribers` but an incoming message is then received for that subscriber. It doesn't seem correct to broadcast that as an error to all remaining subscribers for unrelated messages.
Changes:
* Only broadcast an error to all subscribers if there was no `id` field in the message
* Do not send any error if the `id` was not found in `subscribers`.

fix: Websocket error broadcast for unsubscribed ID

---

Tests/ApolloCodegenTests/CodeGenIR/IRInputObjectTests.swift
apollo-ios-codegen/Sources/GraphQLCompiler/GraphQLSchema.swift
apollo-ios-codegen/Sources/IR/IR+Schema.swift

In some cases, the order of parsed types come out differently on different systems (unclear why). This creates problems in some situations where we're checking in the generated SchemaMetadata files, as we continuously flip back and forth between two orderings, generating git diffs.
By sorting the parsed types, we guarantee that their order is stable and no unnecessary diffs are introduced.

feat(apollo-ios-codegen): Stable sort schema types for SchemaMetadata

---

apollo-ios/Sources/ApolloAPI/DataDict.swift

We encountered a similar [issue](https://github.com/apollographql/apollo-ios/issues/3247) on the macOS 11..<11.3 versions, which has been [fixed](https://github.com/apollographql/apollo-ios-dev/pull/61) for iOS. 
Although the issue was observed on macOS, I suggest including all platforms that could potentially face the same problem.
---
This PR extends the `_AnyHashableCanBeCoerced` check to include macOS, watchOS, and tvOS with their respective minimum versions. 

fix: Bug with AnyHashable coercion for non-iOS platforms

---

.github/workflows/ci-tests-xcode-swift-6.yml
.github/workflows/ci-tests.yml

There is no more Xcode 16.x beta on the GitHub images so this PR updates the version we use for Swift 6 compatibility to Xcode 16.1 which is the latest stable.
Even though a beta of 16.2 is available from Apple now and will probably be available on GitHub in the future I don't think we need to target beta versions specifically any more; Swift 6 is the important piece and that looks to have settled in 16.1.

ci: Update Xcode versions

---

.github/workflows/release-check.yml

I noticed that we've been having some failures on the Main Branch Health job but the test logs aren't being saved.
- Adds the `failure()` condition so that the save steps are still run when the job fails
- Adds pagination tests (not sure why these weren't in here, maybe just forgot when the pagination lib was added)
- Some clean up

ci: Main branch health failure logs

---

Tests/ApolloInternalTestHelpers/MockURLProtocol.swift
Tests/ApolloTests/Network/URLSessionClientTests.swift

We've been getting frequent failures of the `test__request__cancellingTaskThroughClient_shouldNotCallCompletion` test in the [Main Branch Health](https://github.com/apollographql/apollo-ios-dev/actions/workflows/release-check.yml) nightly build. I [fixed the build logs](https://github.com/apollographql/apollo-ios-dev/pull/523) not being archived which lead to the following:
- We shouldn't be using `fatalError` for a missing request handler. I think it's a bad practice and the behaviour obscures the actual test failure by crashing instead.
- Improves the `test__request__cancellingTaskThroughClient_shouldNotCallCompletion` test by invoking the same delegate callback that happens when a task is cancelled. This means we don't need to wait an arbitrary amount of time for the request callback …

ci: Fix `URLSessionClientTest` tests

---

.github/workflows/release-check.yml

Looks like the `jobs` context is not available to the action and there does not seem to be another way to report on the status of all jobs so this just gives us an overall action status message now.

ci: trims nightly build notification message to available context

---

apollo-ios/Sources/ApolloWebSocket/WebSocketTransport.swift

Closes https://github.com/apollographql/apollo-ios/issues/3466.
Assign the callback queue before connecting to prevent potential data race.

fix: Assign websocket callback queue before connecting

---

.github/workflows/ci-tests-xcode-swift-6.yml

GitHub dropped Xcode 16.x versions from the `macos-latest` VM image so we need to switch to `macos-15` VM image to continue testing with it.

ci: Use `macos-15` VM image for Xcode 16.1 tests

---

.github/workflows/ci-tests-xcode-swift-6.yml
.github/workflows/ci-tests.yml
apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/auto_rollup.sh

Here's a couple changes to our CI jobs to hopefully speed up total CI time and reduce mistakes:
* I'm moving `npm install` to the common script so that we don't need to do it separately as part of the JS frontend bundle update. This should mean less mistakes by missing a step that is needed to install the latest package updates. _Stems from the secops PR that failed CI due to the bundle needing to be updated. Couldn't understand why I wasn't getting any changes, then realized I needed to install the package updates before regenerating the bundle. This makes it a common step now so that should all be handled for us._
* The jobs we perform using Xcode 16.1 (Swift 6) should only be the ones that actually use that runtime. So I've removed the jobs from that CI script that aren't affected by …

ci: Minor job improvements

---

apollo-ios/Sources/Apollo/GraphQLQueryWatcher.swift
docs/source/fetching/queries.mdx

Ref https://github.com/apollographql/apollo-ios/issues/3472

Add documentation about using GraphQLQueryWatcher with mutations

---

docs/source/index.mdx

Just noticed these lead to 404s. I believe an absolute link needs to be used for ButtonLinks (didn't notice any others in the ios docs)

Fix getting started button link

---

apollo-ios/README.md

Trying to make it clearer for users to know which version of the GraphQL spec the client is compatible with.

chore: Update readme for GraphQL spec compability

---

apollo-ios/Sources/Apollo/JSONRequest.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3483.
> Given that if the Apollo iOS cache store had expiration features it would obey them I can support the argument that `useProtocolCachePolicy` is an equivalent default more-so than `returnCacheDataElseLoad`. This shouldn't change the behaviour that was implemented for https://github.com/apollographql/apollo-ios/issues/3432 either
The differing behaviour is in whether the cache policy respects the original Cache-Control header directive re. expiration:
* `useProtocolCachePolicy` is [defined](https://developer.apple.com/documentation/foundation/nsurlrequest/cachepolicy/useprotocolcachepolicy) as "Use the caching logic defined in the protocol implementation, if any, for a particular URL load request."
* `returnCacheDataElseLoad` …

fix: Changes `URLRequest` cache policy default

---

docs/source/_redirects

The docs team is centralizing redirects from `_redirects` files into the docs platform repository.  (See https://github.com/apollographql/docs-rewrite/pull/370)
Docs in external repositories can still add redirects in page frontmatter like so:
```
---
title: Apollo GraphOS Platform
description: The GraphQL API Platform
redirectFrom:
- /intro/platform
- /graphos
- /federation/managed-federation/overview
---
```
Redirects in a page's frontmatter take precedence over redirects in the _redirects file but flag a warning.

docs: move redirects

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplate_Initializers_Tests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift

While working on selection set initializers I realized that the current generated initializers do not set the selection set types in the `deferredFragments` property.
Some of the named fragment initializers do not look correct but I believe this is due to https://github.com/apollographql/apollo-ios/issues/3486 and https://github.com/apollographql/apollo-ios/issues/3487. Adding the values to `deferredFragment` will not have any detrimental effect and those will get fixed on top of this work.

fix: `DataDict` initialization of `deferredFragments`

---

CONTRIBUTING.md
apollo-ios/.github/ISSUE_TEMPLATE/question.yaml
docs/source/tutorial/tutorial-subscriptions.mdx

Replace Discord with Discourse links since the Discourse Community Forum there is becoming our focus.

Replace Discord with Discourse

---

Tests/ApolloCodegenTests/CodeGenIR/IRRootFieldBuilderTests.swift

PR #562 highlighted that we are not testing fragment field merging past a depth of 3 entities. While we cannot test for every depth to infinity, this test confirms merging works to a depth of 4 and proves the edge case of that PR.

Add test for merging a fragment with a depth of 4

---

docs/source/get-started.mdx
docs/source/index.mdx

Add meta descriptions and subtitles to help with discoverability of top-level pages

docs: add meta descriptions and subtitles

---

Tests/ApolloTests/Interceptors/MultipartResponseDeferParserTests.swift
Tests/ApolloTests/Interceptors/MultipartResponseSubscriptionParserTests.swift
apollo-ios/Sources/Apollo/MultipartResponseDeferParser.swift
apollo-ios/Sources/Apollo/MultipartResponseParsingInterceptor.swift
apollo-ios/Sources/Apollo/MultipartResponseSubscriptionParser.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3495.
Refactored the parsing of `content-type` to handle multiple directives, which resolved the bug but also removed duplicated code. and allows for all directives to be used.

fix: Multipart chunk content type

---

Tests/ApolloTests/Interceptors/MultipartResponseDeferParserTests.swift
Tests/ApolloTests/Interceptors/MultipartResponseSubscriptionParserTests.swift
Tests/ApolloTests/RequestChainTests.swift
apollo-ios/Sources/Apollo/MultipartResponseDeferParser.swift
apollo-ios/Sources/Apollo/MultipartResponseParsingInterceptor.swift
apollo-ios/Sources/Apollo/MultipartResponseSubscriptionParser.swift
apollo-ios/Sources/Apollo/RequestChainNetworkTransport.swift

Closes https://github.com/apollographql/apollo-ios/issues/3485.
1. Make sure we include the new type in the 'accept' request header.
2. Update tests for new content type.
3. There were no changes needed for error handling because [we do not throw when the response status code falls outside the 200..<300 range](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios/Sources/Apollo/ResponseCodeInterceptor.swift#L60).
4. Our non-multipart response parser does not require that the content type actually be `application/json`. Instead it simply attempts to [deserialize anything as if it is JSON](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios/Sources/Apollo/JSONResponseParsingInterceptor.swift#L54). It's only in the multipart parsers that we do a content type …

feature: Adds support for GraphQL over HTTP media type

---

.github/workflows/ci-tests-xcode-swift-6.yml

Bumps the Xcode version to 16.2 for our "Swift 6" CI jobs.

chore: Use Xcode 16.2 on Swift 6 CI jobs

---

Tests/ApolloCodegenInternalTestHelpers/IRBuilderTestWrapper.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegen.swift
apollo-ios-codegen/Sources/IR/IR+RootFieldBuilder.swift
apollo-ios-codegen/Sources/IR/IRBuilder.swift

Currently, when fragment field merging is disabled we are preventing the fields from being merged into the `MergedSelections` while traversing the built `EntitySelectionTree`. However, the performance issues described in https://github.com/apollographql/apollo-ios/issues/3434 are actually caused during the merging of the fragment fields _into_ the `EntitySelectionTree`s during the building of the operations.
This PR prevents the fragment selection trees from being merged into the `EntitySelectionTree` while building the operations **if fragment field merging is disabled**.
This means that the entity trees are actually incomplete, but they still work for the purposes of Codegen in this scenario. Incomplete `EntitySelectionTree`s would cause selection set initializers to be invalid. But …

Prevent merging of fragment fields into selection tree if fragment field merging is disabled

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/DeferredFragmentsMetadataTemplateTests.swift
Tests/ApolloCodegenTests/CodeGeneration/Templates/OperationDefinitionTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/DeferredFragmentsMetadataTemplate.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/OperationDefinitionTemplate.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3503
This implements solution 2 in the issue description for the following reasons:
* This diff is minimal and resolves the issue for all module types. We could keep the extension but we're going to end up with multiple templates that need to handle the metadata insertion = IMO less optimal.
* I don't see any benefit to having the defer metadata within the same file but in an extension. The metadata is partitioned with a `MARK` comment line.
* Operation files also do not support custom edits so there is no need to preserve anything about previously generated operation files.

fix: Defer metadata extensions

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift
apollo-ios-codegen/Sources/IR/IR+ComputedSelectionSet.swift

This is a rework of #548, except this time it will only emit a conformance if the `keyFields` is set to exactly `["id"]` (instead of assuming the presence of an `id` field is enough).
If a type has a field named `id` it is actually impossible to override the behavior of `Identifiable`, so I believe there is no situation in which an automatic conformance to Identifiable isn't desirable.
This PR will not generate a getter named `id` (as was proposed earlier), so there won't be an unexpected field named `id` in any case.

feature: Emit Identifiable conformance on SelectionSets

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplate_Initializers_Tests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift

_Discovered this bug when working on the selection set initializers for defer._
When deferred fragments are named fragments the deferred type is the fragments generated definition name.

fix: `DataDict` initialization of `deferredFragments` for named fragments

---

.github/workflows/check-pr-metadata.yml

I noticed that the 'Check PR Metadata' CI check was not always running or failing with the following error:
> GraphQL: Resource not accessible by integration (addComment)
I did some reading and from [this issue](https://github.com/cli/cli/issues/8374#issuecomment-1840846179) it seems as if the correct event to base the action on is `pull_request_target` rather than `pull_request` because of the need to elevate permissions for the action. The following in the [GitHub documentation for `pull_request_target`](https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target) is the relevant section:
> This event runs in the context of the base of the pull request, rather than in the context of the …

ci: Use trigger event with base branch context

---

docs/source/client-directives.mdx

The document has `module` instead of `keyFields` as the parameter name.

Fix documentation for @typePolicy directive

---

Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Fragments/PetDetails.graphql.swift
Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/LocalCacheMutations/PetSearchLocalCacheMutation.graphql.swift
Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Operations/Mutations/PetAdoptionMutation.graphql.swift
Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Operations/Queries/AllAnimalsIncludeSkipQuery.graphql.swift
Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Operations/Queries/AllAnimalsQuery.graphql.swift
Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Operations/Queries/DogQuery.graphql.swift
Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Operations/Queries/FindPetQuery.graphql.swift
Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Operations/Queries/PetSearchQuery.graphql.swift
Sources/AnimalKingdomAPI/animalkingdom-graphql/PetDetails.graphql
Tests/ApolloCodegenTests/CodeGeneration/Templates/FragmentTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/FragmentTemplate.swift
apollo-ios-codegen/Sources/IR/GraphQLCompositeType+Identifiable.swift
apollo-ios-codegen/Sources/IR/IR+ComputedSelectionSet.swift
apollo-ios-codegen/Sources/IR/IR+NamedFragment.swift

This does the same as #584, except for generated NamedFragment types.

feature: Identifiable conformance for Named Fragments

---

.github/workflows/ci-tests-xcode-swift-6.yml
.github/workflows/ci-tests.yml
.github/workflows/release-check.yml

PRs are currently failing multiple workflows with this error:
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
It seems relatively straight-forward considering our simple use of the action, but the thing that jumped out to me was:
> In v4, users lose the ability to upload to the same named artifact multiple times. Once an artifact is uploaded cannot be altered, **and there cannot be multiple v4 artifacts with the same name, in the same workflow run.**
I think we're fine here because we use the `upload-artifact` action in three workflows but they're separate workflows not jobs within the same workflow. The jobs we do …

ci: Update to use upload-artifact@v4 action

---

.github/workflows/ci-tests-xcode-swift-6.yml
.github/workflows/ci-tests.yml
.github/workflows/release-check.yml
Tests/ApolloTests/InputDictTests.swift
apollo-ios/Sources/ApolloAPI/SchemaTypes/InputObject.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3506.
`InputObject` needed a `GraphQLNullable`-specific subscript to prevent `nil` value keys being forcefully unwrapped.

fix: InputObject GraphQLNullable subscript

---

apollo-ios/Sources/ApolloWebSocket/WebSocketTransport.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3512
This data race can happen if is a start/stop subscription at the same time as a message received on the websocket getting processed. The `subscribers` property is accessed from two threads at the same time causing a crash. 
I am not really sure how I can add unit tests for this change. The data race type tests are really hard to write.

Fix data race for subscribers property

---

.github/workflows/update-swift-js-bundle.yml

Some of the secops PRs require that the Swift JS bundle be updated so that there is no diff detected with the updated dependencies. It has so far been a manual process, this changes that so CI can do it for us.

ci: Adds new workflow for Swift JS bundle updates

---

Sources/AnimalKingdomAPI/AnimalKingdomAPI/Package.swift
Sources/GitHubAPI/GitHubAPI/Package.swift
Sources/StarWarsAPI/StarWarsAPI/Package.swift
Sources/SubscriptionAPI/SubscriptionAPI/Package.swift
Sources/UploadAPI/UploadAPI/Package.swift
SwiftScripts/Sources/TargetConfig/Module.swift

Updating the spm config for testing apis to use local `apollo-ios` pathing

Updating package config for test apis

---

Tests/ApolloTests/MutatingSelectionSetTests.swift
Tests/ApolloTests/SelectionSetTests.swift
apollo-ios/Sources/ApolloAPI/LocalCacheMutation.swift

This addresses the limitations described in https://github.com/apollographql/apollo-ios/issues/3443. This is solved by adding a new `mutateIfFulfilled` function that only allows for the properties of an inline fragment to be mutated if the fragment already is fulfilled, while still preventing a fragment from being added/removed from an existing model.

Add mutateIfFulfilled functions

---

Tests/ApolloTests/RequestContextTests.swift
Tests/ApolloTests/RequestContextTimeoutTests.swift
apollo-ios/Sources/Apollo/HTTPRequest.swift
apollo-ios/Sources/Apollo/RequestContext.swift

Closes https://github.com/apollographql/apollo-ios/issues/3522.
The _desired_ solution mentioned in the issue was to introduce an additional parameter on the `fetch` and `send` functions. That solution would have introduced a breaking change due to those functions being part of the protocols `ApolloClientProtocol` and `NetworkTransport` respectively.
The solution implemented in this PR is to leverage the `RequestContext` marker protocol and introduce a configuration specific sub-protocol. The idea is that this can be extended in the future to introduce more request configuration parameters as needed. It also is not a breaking change.

feature: Configure `URLRequest` timeout interval

---

Tests/ApolloTests/Interceptors/MultipartResponseParsingInterceptorTests.swift
apollo-ios/Sources/Apollo/MultipartResponseParsingInterceptor.swift

Related to https://github.com/apollographql/apollo-ios/issues/3536#issuecomment-2763230360.
It takes a bit of [familiarity with the multipart parsing interceptor](https://github.com/apollographql/apollo-ios/issues/3536#issuecomment-2762950300) to understand why responses like that in the above issue fail. These new error messages should provide more context to help others understand why the response might be failing.

refactor: More contextual multipart parsing errors

---

.package.resolved
Tests/ApolloTests/AutomaticPersistedQueriesTests.swift
apollo-ios/Package.swift
apollo-ios/Sources/Apollo/ApolloStore+ReaderWriter.swift
apollo-ios/Sources/Apollo/ApolloStore.swift

Creates a `ReaderWriter` using `SwiftAtomics` that allows for multiple parallel reads while locking for writes.
This will replace the current barrier queue for ApolloStore. Usage of this will be implemented in stacked PR.

[v2] [1/X] ApolloStore async Read/Write lock

---

Tests/ApolloCodegenTests/ApolloCodegenTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegen.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/CodegenConfiguration/ApolloCodegenConfiguration.swift
apollo-ios/ROADMAP.md

Fixes https://github.com/apollographql/apollo-ios/issues/3554
The full set of selection set initializers must always be generated for local cache mutation operations and fragments. Before this change using a `fieldMerging` policy of anything other than `none` would generate local cache mutations but they could not be initialized and did not contain all the correct merged fields.

fix: Local cache mutation generation when field merging disabled

---

apollo-ios/Sources/ApolloSQLite/SQLiteDatabase.swift

Add a public initializer to `DatabaseRow` to enable custom `SQLiteDatabase` implementations
The `SQLiteNormalizedCache` is nicely structured with protocols so that consumers of the library can implement their own components under the hood if they choose to. There are a couple reasons one might want to do this:
* to use a different SQLite implementation (mentioned as a goal in [a comment on the original dependency inversion PR](https://github.com/apollographql/apollo-ios/pull/1722#discussion_r595590746))
* to add custom functionality under the hood, like a TTL policy for rows in the cache (I am trying to follow this path, motivating this PR)
All of that is possible! ...almost
The use of `SQLiteDatabase` protocol makes it easy to implement and inject your own implementation, with one …

Custom SQLiteDatabase Implementations

---

apollo-ios/Sources/Apollo/ApolloClient.swift
apollo-ios/Sources/Apollo/ApolloClientProtocol.swift
apollo-ios/Sources/Apollo/AsyncThrowingStream+ExecutingInAsyncTask.swift
apollo-ios/Sources/Apollo/FetchBehavior.swift
apollo-ios/Sources/Apollo/GraphQLQueryWatcher.swift
apollo-ios/Sources/Apollo/NetworkTransport.swift
apollo-ios/Sources/Apollo/RequestChain.swift
apollo-ios/Sources/Apollo/RequestChainNetworkTransport.swift
apollo-ios/Sources/ApolloAPI/GraphQLOperation.swift
apollo-ios/Sources/ApolloWebSocket/SplitNetworkTransport.swift

This PR :
- Creates the new APIs for Mutation and Upload requests on `ApolloClient` and `NetworkTransport`.
- Reimagines `SplitNetworkTransport` as a generic type that allows for more flexible use cases.
- Aligns `ApolloClientProtocol` with new APIs
- Cleans up a lot of the documentation and code

[v2] [14/X] NetworkTransport and Client Cleanup

---

apollo-ios/Sources/Apollo/ApolloClient.swift
apollo-ios/Sources/Apollo/ApolloClientProtocol.swift
apollo-ios/Sources/Apollo/ApolloStore.swift
apollo-ios/Sources/Apollo/AsyncThrowingStream+ExecutingInAsyncTask.swift
apollo-ios/Sources/Apollo/CachePolicy.swift
apollo-ios/Sources/Apollo/Cancellable.swift
apollo-ios/Sources/Apollo/FetchBehavior.swift
apollo-ios/Sources/Apollo/GraphQLQueryWatcher.swift
apollo-ios/Sources/Apollo/NetworkTransport.swift
apollo-ios/Sources/Apollo/RequestChain.swift
apollo-ios/Sources/Apollo/RequestChainNetworkTransport.swift
apollo-ios/Sources/ApolloAPI/GraphQLOperation.swift
apollo-ios/Sources/ApolloWebSocket/SplitNetworkTransport.swift

The `GraphQLQueryWatcher` is now an `Actor` to ensure its thread safety. Significant changes to the implementation have been made to use structured concurrency, but the usage stays very similar.
Only significant difference is that I removed the `refetch()` function. The fetch functions are now public and there are overloads for all cache policies and `FetchBehavior`.

[v2] [13/X] Refactor GraphQLQueryWatcher

---

Tests/ApolloInternalTestHelpers/MockNetworkTransport.swift
Tests/ApolloInternalTestHelpers/XCTestCase+Helpers.swift
Tests/ApolloPerformanceTests/ParsingPerformanceTests.swift
Tests/ApolloTests/CancellationHandlingInterceptor.swift
Tests/ApolloTests/GraphQLResultTests.swift
Tests/ApolloTests/Interceptors/GraphQLInterceptor_ErrorHandling_Tests.swift
Tests/ApolloTests/JSONResponseParser_SingleResponseParsingTests.swift
Tests/ApolloTests/JSONTests.swift
apollo-ios/Sources/Apollo/ApolloClient.swift
apollo-ios/Sources/Apollo/ApolloClientProtocol.swift
apollo-ios/Sources/Apollo/ApolloStore.swift
apollo-ios/Sources/Apollo/GraphQLQueryWatcher.swift
apollo-ios/Sources/Apollo/GraphQLResult.swift
apollo-ios/Sources/Apollo/Interceptors/ApolloInterceptor.swift
apollo-ios/Sources/Apollo/Interceptors/CacheInterceptor.swift
apollo-ios/Sources/Apollo/Interceptors/JSONResponseParsingInterceptor.swift
apollo-ios/Sources/Apollo/JSONConverter.swift
apollo-ios/Sources/Apollo/NetworkTransport.swift
apollo-ios/Sources/Apollo/RequestChain.swift
apollo-ios/Sources/Apollo/RequestChainNetworkTransport.swift
apollo-ios/Sources/Apollo/ResponseParsing/JSONResponseParser.swift
apollo-ios/Sources/Apollo/ResponseParsing/SingleResponseExecutionHandler.swift
apollo-ios/Sources/Apollo/SplitNetworkTransport.swift
apollo-ios/Sources/ApolloWebSocket/WebSocketTransport.swift

This PR renames `GraphQLResult` to `GraphQLResponse`. "Response" is more accurate to what this actually _is_. 
We used to have an internal type in 1.0 called `GraphQLResponse` which handled parsing the response data into the `GraphQLResult`. 2.0 removes this struct and handles parsing through a `JSONResponseParser` object. This allows us to use the name `GraphQLResponse` where it is more accurate in the public API.
The intermediary struct that is created by the `JSONResponseParser` is now named `ParsedResult`. This struct just holds a `GraphQLResponse` and the cache records to be written to the cache.
---
This PR also changes the new `GraphQLResponse` struct to be generic over the `GraphQLOperation` instead of the operation's `Data` object directly. I think this is more expressive and …

[v2] Refactor GraphQLResult

---

Tests/ApolloTests/Interceptors/JSONResponseParsingInterceptor_MultipartResponseSubscriptionParser_Tests.swift
apollo-ios/Sources/Apollo/ResponseParsing/MultipartResponseSubscriptionParser.swift

`MultipartResponseSubscriptionParser.ParsingError.irrecoverableError(message: String)` has been changed to `irrecoverableErrors([GraphQLError])`.
This change is due to a user request. When there are multiple errors, they should all be exposed to the user.

[v2] Exposed all errors in multipart subscription parser 

---

Tests/ApolloTests/ApolloStore_BatchedLoadTests.swift
Tests/ApolloTests/Cache/DeferOperationCacheReadTests.swift
Tests/ApolloTests/Cache/LoadQueryFromStoreTests.swift
Tests/ApolloTests/Cache/ReadWriteFromStoreTests.swift
Tests/ApolloTests/Cache/SQLite/CachePersistenceTests.swift
Tests/ApolloTests/Interceptors/MaxRetryInterceptorTests.swift
Tests/ApolloTests/RequestChainNetworkTransportTests.swift
apollo-ios/Sources/Apollo/ApolloClient.swift
apollo-ios/Sources/Apollo/ApolloClientProtocol.swift
apollo-ios/Sources/Apollo/ApolloStore.swift
apollo-ios/Sources/Apollo/CachePolicy.swift
apollo-ios/Sources/Apollo/GraphQLQueryWatcher.swift
apollo-ios/Sources/Apollo/RequestBodyCreator.swift
apollo-ios/Sources/Apollo/RequestChain.swift
apollo-ios/Sources/Apollo/SplitNetworkTransport.swift
apollo-ios/Sources/ApolloAPI/JSONDecodingError.swift
apollo-ios/Sources/ApolloSQLite/ApolloSQLiteDatabase.swift

This PR changes the behavior of a cache miss to return `nil` rather than throwing a `JSONDecodingError.missingValue`. A cache miss is an expected possibility, not necessarily an error, and this can cause confusion for users. Now the cache loading mechanisms only throw an error if there is a problem with the cache, such as corrupt or invalid data.

[v2] Return nil on cache miss

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/DeferredFragmentsMetadataTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/DeferredFragmentsMetadataTemplate.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3565.
The deferred fragment identifier was being generated using all elements in the deferred fragments path type info array. While the contents of that array are correct because of the unique selection sets, the identifier is able to be shared amongst elements with the same path and defer condition. Taking this into account the identifiers are now generated without duplicates.

fix: Duplicate deferred fragment identifiers

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplateTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3567
The selection set template would correctly produce a fragment accessor property for merged deferred fragments but the initializer was missing.

fix: Deferred fragment accessor with nested fragment

---

Tests/ApolloCodegenTests/CodeGeneration/Templates/InputObjectTemplateTests.swift
Tests/ApolloTests/InputDictTests.swift
apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/InputObjectTemplate.swift
apollo-ios/Sources/ApolloAPI/SchemaTypes/InputObject.swift

In 2.0 we remove conformance of `Optional` to `GraphQLOperationVariableValue` because it should always be stored as a `GraphQLNullable`.
This caused a few issues addressed by this PR:
On a generated InputObject, non-null fields with a schema defined default value are generated as `Optional`. Because they either are a value or `nil` (using the default value of the schema) they can't be `.null` like a nullable field. Since `Optional` cannot be stored as a variable any more, the generated input object failed to compile.
This PR:
1. Adds a new subscript to `InputDict` that converts the `GraphQLNullable` to the `Optional` field value (and vice versa for the setter).
2. Converts the `Optional` value in the input objects initializer to `GraphQLNullable` in the code generation template.

[v2] Fix Input Object

---

apollo-ios/Sources/Apollo/NetworkTransport.swift

Fixes https://github.com/apollographql/apollo-ios/issues/3570.
This changes the version/build delimiter from a `-` to a `+`. This now matches [the semver specification of that additional metadata](https://semver.org/#spec-item-10).
> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3----117B344092BD.
**Note:** This does not address the …

fix: change clientVersion build delimiter

---

Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Schema/InputObjects/PetSearchFilters.graphql.swift
Sources/AnimalKingdomAPI/animalkingdom-graphql/AnimalSchema.graphqls
Tests/ApolloTests/GraphQLOperationVariableEncodingTests.swift
apollo-ios/Sources/ApolloAPI/GraphQLOperation.swift
apollo-ios/Sources/ApolloAPI/ScalarTypes.swift
apollo-ios/Sources/ApolloAPI/SchemaTypes/EnumType.swift

https://github.com/apollographql/apollo-ios/commit/2832c18e485d1b9f6b76f64b919c31a2b0268a9a prevented optional values from being used in inputs. Because all nullable values should use `GraphQLNullable` not `Optional` in inputs. But when you have a list of optional elements, you should still use `Optional`. Inside of the list `Optional.none` is treated as `null`, there is no need for discerning between `.none` and `.null`.
This PR adds a new `GraphQLOperationVariableListElement` protocol to differentiate between values that can be a top-level variable value and those that can only be list elements. It also adjusts the conformances of types to these protocols to represent the desired intent accurately.

[v2] Fix nullable list of nullable items in InputObject

---

.github/workflows/ci-tests.yml
.github/workflows/release-check.yml

Nightly health builds are [failing](https://github.com/apollographql/apollo-ios-dev/actions/workflows/release-check.yml) because `macos-15` no longer has Xcode 15 installed so we need to move back to `macos-14` for this branch. When 2.0 is merged into `main` we'll get back on the `macos-15` image platform.

fix: Move to `macos-14` for actions image platform

---

Tests/ApolloTests/RequestChainNetworkTransportTests.swift
apollo-ios/Sources/Apollo/RequestChainNetworkTransport.swift
apollo-ios/Sources/ApolloWebSocket/WebSocketTransport.swift

I forgot to make `RequestChainNetworkTransport` conform to `SubscriptionNetworkTransport` protocol. All of the underlying mechanisms to support this already exist.
We will need to add more tests for this functionality in the near future, but just need this enabled for the 2.0 release.

Add subscription support to request chain network transport

---

.github/workflows/nightly-health-check.yml

* Changed the Xcode version used for the nightly health check; `16.4`
* Updated test architecture to match CI test; `arm64`.
* Renamed the action file to reflect it's purpose.

Fix: Xcode version for nightly health check
