apollographql/apollo-ios-dev

- .github/workflows/pr-subtree-push.yml
- docs/source/code-generation/run-codegen-in-swift-code.mdx
Making some minor updates to the codegen docs to reference the new `apollo-ios-codegen` spm package
> Minor codegen docs updates

- apollo-ios-codegen/Sources/ApolloCodegenLib/Frontend/JavaScript/src/__tests__/deferDirectiveTests.ts
- apollo-ios-codegen/Sources/ApolloCodegenLib/Frontend/JavaScript/src/validationRules.ts
Closes https://github.com/apollographql/apollo-ios/issues/3187
Adds validation to the frontend JS to ensure that all `@defer` directives specify a `label` argument.
> feature: Require `label` argument on `@defer` directive

- SwiftScripts/Sources/TargetConfig/Target.swift
- Tests/ApolloCodegenTests/ApolloCodegenConfigurationCodableTests.swift
- Tests/ApolloCodegenTests/CodeGeneration/Templates/LocalCacheMutationDefinitionTemplateTests.swift
- Tests/ApolloCodegenTests/CodeGeneration/Templates/OperationDefinitionTemplateTests.swift
- Tests/ApolloTests/GraphQLExecutor_SelectionSetMapper_FromResponse_Tests.swift
- apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegen.swift
- apollo-ios-codegen/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift
- apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/LocalCacheMutationDefinitionTemplate.swift
- apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/OperationDefinitionTemplate.swift
- apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/TemplateRenderer.swift
- apollo-ios/.github/PULL_REQUEST_TEMPLATE/pull-request-template-release.md
- apollo-ios/CHANGELOG.md
- apollo-ios/ROADMAP.md
- apollo-ios/Sources/ApolloWebSocket/DefaultImplementation/WebSocket.swift
- docs/source/code-generation/codegen-configuration.mdx
Updating the `project-breakup` branch to current `apollo-ios` main
> Updating to current main

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
Fixing subtree issue caused by secops changes to codegen subtree by manually pulling subtree and updating
> Subtree updates

- .github/workflows/pr-subtree-push.yml
- Project.swift
- apollo-ios-pagination/.github/renovate.json5
- apollo-ios-pagination/.gitignore
- apollo-ios-pagination/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
- apollo-ios-pagination/LICENSE
- apollo-ios-pagination/Package.resolved
- apollo-ios-pagination/Package.swift
- apollo-ios-pagination/README.md
- apollo-ios-pagination/Sources/ApolloPagination/AnyGraphQLPager.swift
- apollo-ios-pagination/Sources/ApolloPagination/CursorBasedPagination/CursorBasedPagination.swift
- apollo-ios-pagination/Sources/ApolloPagination/CursorBasedPagination/ForwardPagination.swift
- apollo-ios-pagination/Sources/ApolloPagination/CursorBasedPagination/ReversePagination.swift
- apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPager+Convenience.swift
- apollo-ios-pagination/Sources/ApolloPagination/GraphQLQueryPager.swift
- apollo-ios-pagination/Sources/ApolloPagination/OffsetBasedPagination/OffsetPagination.swift
- apollo-ios-pagination/Sources/ApolloPagination/PaginationError.swift
- apollo-ios-pagination/Sources/ApolloPagination/PaginationInfo.swift
- apollo-ios-pagination/Sources/ApolloPagination/UpdateSource.swift
Adding the `apollo-ios-pagination` repo as a subtree to enable development of this feature in the `apollo-ios-dev` environment.
> Add apollo-ios-pagination subtree

- .github/workflows/pr-subtree-push.yml
This PR: 
- Updates the target branch for Apollo-iOS-Pagination pushes.
> Update target branch for Apollo-iOS-Pagination

- .github/actions/build-and-run-unit-tests/action.yml
- .github/workflows/ci-tests.yml
- .github/workflows/release-check.yml
- Tests/TestCodeGenConfigurations/Other-CocoaPods/test-project.sh
- Tests/TestCodeGenConfigurations/Other-CustomTarget/test-project.sh
- Tests/TestCodeGenConfigurations/SPMInXcodeProject/test-project.sh
Removing the usage of `xcbeautify` from the CI
> Removing xcbeautify usage

- .github/workflows/release-check.yml
Removing the test for iOS 14.4 for now until we can come up with a solution to get it working correctly in github actions.
> Removing legacy iOS version test for now

- .github/workflows/ci-tests.yml
- .github/workflows/release-check.yml
Seems like 15.0.0 is no longer available.
> Fix CI by updating Xcode version to 15.0.1

- .github/actions/build-and-run-unit-tests/action.yml
- .github/workflows/ci-tests.yml
- .github/workflows/release-check.yml
- Tests/TestCodeGenConfigurations/Other-CocoaPods/test-project.sh
- Tests/TestCodeGenConfigurations/Other-CustomTarget/test-project.sh
- Tests/TestCodeGenConfigurations/SPMInXcodeProject/test-project.sh
Adding xcbeautify back to ci since we aren't currently running older os tests where its not supported
> Adding back xcbeautify

- docs/source/config.json
- docs/source/migrations/1.5.mdx
Closes https://github.com/apollographql/apollo-ios/issues/3230.
> docs: Add 1.5 migration guide

- .github/workflows/ci-tests.yml
-Adding checks for changes to ios and codegen code
-Updating jobs to only run if changes were made in relevant areas of the code
> Adding optimizations to ci tests

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
Combined PR for:
* https://github.com/apollographql/apollo-ios-dev/pull/206
* https://github.com/apollographql/apollo-ios-dev/pull/204
* https://github.com/apollographql/apollo-ios-dev/pull/203
> chore(deps): Combined dependency updates

- apollo-ios-codegen/.circleci/config.yml
- apollo-ios-pagination/.circleci/config.yml
- apollo-ios/.circleci/config.yml
This is a collection of the following PRs since we don't allow PRs in the individual repos:
- https://github.com/apollographql/apollo-ios/pull/3312#event-11434477576
- https://github.com/apollographql/apollo-ios-codegen/pull/11#event-11434479721
- https://github.com/apollographql/apollo-ios-pagination/pull/20
> feat: SECOPS-2525 - add semgrep job

- apollo-ios/.github/workflows/issue-close-user-survey.yml
This change avoids posting the user survey comment in forked repos.
> chore: User survey update

- apollo-ios/.github/workflows/issue-close-user-survey.yml
I forgot the multiline character for the script, and a better bash number comparison.
> chore: Fix user survey actions script

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
Supersedes:
* https://github.com/apollographql/apollo-ios-dev/pull/269
* https://github.com/apollographql/apollo-ios-dev/pull/271
* https://github.com/apollographql/apollo-ios-dev/pull/273
> chore: SECOPS Renovate Updates

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
A combined PR of:
* https://github.com/apollographql/apollo-ios-dev/pull/294
* https://github.com/apollographql/apollo-ios-dev/pull/295
> chore(deps): SECOPS updates

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
- apollo-ios/.github/workflows/prometheus-project-add.yml
Combined PRs:
* https://github.com/apollographql/apollo-ios-dev/pull/311
* https://github.com/apollographql/apollo-ios-dev/pull/314
> secops: 2024-03-25

- docs/source/testing/test-mocks.mdx
the definite article should be a relative pronoun, meaning "to ensure"
> test-mocks.mdx - fix spelling

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
- apollo-ios/.github/workflows/prometheus-project-add.yml
This is the following PRs combined into one for the sake of subtree coordination and delays:
- https://github.com/apollographql/apollo-ios-dev/pull/338/files
- https://github.com/apollographql/apollo-ios-dev/pull/339/files
- https://github.com/apollographql/apollo-ios-dev/pull/340/files
> chore(deps): SECOPS - 2024-04-22

- Tests/ApolloTests/GraphQLExecutor_SelectionSetMapper_FromResponse_Tests.swift
Converting from XCTest based expressions to Nimble.
> defer: Refactor selection set mapper tests to use Nimble

- Tests/ApolloServerIntegrationTests/SchemaRegistryApolloSchemaDownloaderTests.swift
- Tests/ApolloServerIntegrationTests/StarWarsApolloSchemaDownloaderTests.swift
Fixing broken integration tests from schema type renaming work
> Fixing broken integration tests

- README.md
- apollo-ios-pagination/README.md
- apollo-ios/README.md
See https://github.com/apollographql/apollo-ios/pull/3405
> [README] Add dark mode logo

- README.md
Updates "Who is Apollo" text and links.
> Update "Who is Apollo?"

- .github/actions/subtree-split-push/action.yml
- .github/workflows/pr-subtree-push.yml
Passing the pr title inputs into an environment variable to use in git commands to handle escaping the pr title for extra quotes etc
> PR Title handling update

- docs/source/fetching/persisted-queries.mdx
- docs/source/file-uploads.mdx
Updates uses of "Apollo Router" to "GraphOS Router" or "Apollo Router Core" where necessary
> Update router terms

- .github/workflows/create-release-pr.yml
Fixing https://github.com/apollographql/apollo-ios-dev/pull/435/files#r1696119023.
> chore: Remove unnecessary publish release step

- Sources/AnimalKingdomAPI/AnimalKingdomAPI/TestMocks/Bird+Mock.graphql.swift
- Sources/AnimalKingdomAPI/AnimalKingdomAPI/TestMocks/Cat+Mock.graphql.swift
- Sources/AnimalKingdomAPI/AnimalKingdomAPI/TestMocks/Crocodile+Mock.graphql.swift
- Sources/AnimalKingdomAPI/AnimalKingdomAPI/TestMocks/Dog+Mock.graphql.swift
- Sources/AnimalKingdomAPI/AnimalKingdomAPI/TestMocks/Fish+Mock.graphql.swift
- Sources/AnimalKingdomAPI/AnimalKingdomAPI/TestMocks/Human+Mock.graphql.swift
- Sources/AnimalKingdomAPI/AnimalKingdomAPI/TestMocks/Mutation+Mock.graphql.swift
- Sources/AnimalKingdomAPI/AnimalKingdomAPI/TestMocks/Query+Mock.graphql.swift
- Sources/AnimalKingdomAPI/AnimalKingdomAPI/TestMocks/Rat+Mock.graphql.swift
Applying some of the latest codegen changes to the internal generated APIs.
> chore: Updates AnimalKingdomAPI generated test mocks

- docs/source/get-started.mdx
- docs/source/index.mdx
Adds a callout/link to a relevant GraphQL summit workshop
> docs: add summit callout

- Tests/ApolloPaginationTests/OffsetTests.swift
I noticed this test was flaky. This PR fixes that flaky test.
This test is identical to the `AsyncGraphQLQueryPagerTests.test_concatenatesPages_matchingInitialAndPaginated` test, but for use with an offset-based pagination strategy. I updated the test to follow the same logic as that test, which is more reliable.
No.
Change does not run in production. No impact on users. (Documentation or some configuration changes)
- **Rollback** - This change can only be disabled by reverting this pull request or commit.
CI Passes. 
I ran this test 100 times repeatedly, 5x (i.e., 500 runs) locally and it passed every time.
> Fix flaky OffsetPagination test

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package-lock.json
- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
This PR is combining the dependency updates from the following PRs:
#510 
#513 
#515
> chore(deps): Combining multiple dependency update PRs into one

- .github/workflows/release-check.yml
First attempt at a Slack notification..
> ci: `main` branch health build notification

- .github/workflows/release-check.yml
Hoping this is a way to get jobs status into the notification..
> ci: Adds job status to notification

- .github/workflows/release-check.yml
> ci: final update to nightly build notification text

- docs/source/fetching/queries.mdx
Fixing a broken link introduced in https://github.com/apollographql/apollo-ios-dev/pull/543.
> docs: Fix link

- docs/source/fetching/queries.mdx
Clarification related to https://github.com/apollographql/apollo-ios-dev/pull/543#issuecomment-2490892876.
> docs: Clarify normalization comment re. query watcher

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package-lock.json
- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
Combined PR for:
* https://github.com/apollographql/apollo-ios-dev/pull/568
* https://github.com/apollographql/apollo-ios-dev/pull/566
* https://github.com/apollographql/apollo-ios-dev/pull/565
* https://github.com/apollographql/apollo-ios-dev/pull/564
> chore(deps): secops combined PRs - Jan 6th

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package-lock.json
- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
Combination of the following PRs:
1. https://github.com/apollographql/apollo-ios-dev/pull/610
2. https://github.com/apollographql/apollo-ios-dev/pull/609
3. https://github.com/apollographql/apollo-ios-dev/pull/611
> chore(deps): combined secops

- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package-lock.json
- apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json
Combination of:
* https://github.com/apollographql/apollo-ios-dev/pull/624
* https://github.com/apollographql/apollo-ios-dev/pull/625
> chore(deps): combined secops PRs

- Tests/ApolloTests/Cache/LoadQueryFromStoreTests.swift
- apollo-ios/Sources/Apollo/ExecutionSources/CacheDataExecutionSource.swift
Fixes https://github.com/apollographql/apollo-ios/issues/3527
Null list items would previously generate a `wrongType` error if stored and read from the cache. This refactors the execution logic to correctly handle values from cache references in lists.
> fix: Cache read null list item

- apollo-ios-codegen/Sources/ApolloCodegenLib/CodegenConfiguration/ApolloCodegenConfiguration.swift
Closes apollographql/apollo-ios#3563
> Adding @_disfavoredOverload for deprecated initializers

- Tests/ApolloCodegenTests/CodeGeneration/Templates/TemplateRenderer_TestMockFile_Tests.swift
- apollo-ios-codegen/Sources/ApolloCodegenLib/Templates/TemplateRenderer.swift
Closes apollographql/apollo-ios#3566
> Making import of schema module in test mock files @testable

- apollo-ios/README.md
Before marking as ready for review:
> New README info architecture and content
